/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Usuarios;

import ClasesAuxiliares.Variables;
import Controlador.Ejemplo;
import Controlador.Usuarios.ClientesDao;
import Controlador.Usuarios.DetalleFacturaDao;
import Controlador.Usuarios.FacturasDao;
import Controlador.Usuarios.HoraFecha;
import Controlador.Usuarios.ImpresionDao;
import Controlador.Usuarios.MarcasDao;
import Controlador.Usuarios.ModelosDao;
import Controlador.Usuarios.ProductosDao;
import Modelo.Clientes;
import Modelo.DetalleFactura;
import Modelo.Facturas;
import Modelo.Marcas;
import Modelo.Modelos;
import Vista.Principal;
import static Vista.Principal.desktopPane;
import static Vista.Usuarios.Crear_Facturas.secuenciaFac;
import Vlidaciones.ProgressBar;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class BuscarFacturas extends javax.swing.JInternalFrame {

    /**
     * Creates new form FBUsuarios
     */
    Integer clicJtable = -1;
    Integer rowSeleccionadaJTable = -1;
    Facturas facturas1 = new Facturas();
    ProgressBar msg = new ProgressBar(3000, "");
    DefaultTableModel modelo = null;
    public static String secfacturareimpprimr = "";
    public static String tipo_doc_seleccionado = "";

    //String sql_allss = "select * from usuarios";
    // String sql_all = "select usuarios.*,tipos_usuarios.tipo from usuarios inner join tipos_usuarios on tipos_usuarios.codigo=usuarios.Tipo_Usuario_codigo order BY usuarios.Nombres LIMIT 0, 50";
    //CUsuarios obj = new CUsuarios();
    public BuscarFacturas() {

        initComponents();
//this.setSize(1024, 720);
        this.setSize(1098, 695);
        
       
        String[] titulos
                = {"Codigo", "Fecha", "Numero de Factura", "Total",
                    "Vendedor", "Terminal",
                    "Cliente", "Ruc", "Estado"};

        modelo = new DefaultTableModel(null, titulos) {
            @Override
            public boolean isCellEditable(int row, int column) {
                // make read only fields except column 0,13,14
                return column == 3 || column == 4 || column == 5 || column == 7;
                //  return false;
            }
        };
        tipo_doc_seleccionado = "FACTURA";
        jTable1.setModel(modelo);
        jTable1.setRowHeight(25);
        setFechayHoraActualJDChooser();
        if (JRFACTURAS.isSelected()) {
            tipo_doc_seleccionado = "FACTURA";
            llenarjtable();
        }

//        FacturasDao obj = new FacturasDao();
//        String fechaInicio = HoraFecha.fecha_aa_mm_dd_HH_mm_ss(jdchoserdesde.getDate().toString());
//        String fechaFIn = HoraFecha.fecha_aa_mm_dd_HH_mm_ss(jdchoserhasta.getDate().toString());
//
//        jTable1.setModel(obj.listarFacturasTbModel(fechaInicio, fechaFIn, tipo_doc_seleccionado));
//        this.ocultarFIlasJtable();
//        llenarjtable();
//this.setMaximum(true);
    }

    public void llenarjtable() {
        jTable1.setModel(modelo);
        jTable1.setRowHeight(25);

        //   setFechayHoraActualJDChooser();
        FacturasDao obj = new FacturasDao();
        String fechaInicio = HoraFecha.fecha_aa_mm_dd_HH_mm_ss(jdchoserdesde.getDate().toString());
        String fechaFIn = HoraFecha.fecha_aa_mm_dd_HH_mm_ss(jdchoserhasta.getDate().toString());

        jTable1.setModel(obj.listarFacturasTbModel(fechaInicio, fechaFIn, tipo_doc_seleccionado));
        this.ocultarFIlasJtable();
    }

    private void setFechayHoraActualJDChooser() {
        HoraFecha ob = new HoraFecha();
        ob.getHoraActualmyMachine();
        Date inicio = ob.fechaActual_00_00_00();
        Date fin = ob.fechaActual_23_59_59();
        jdchoserdesde.setDate(inicio);
        jdchoserhasta.setDate(fin);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jdchoserdesde = new com.toedter.calendar.JDateChooser();
        jdchoserhasta = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_hoy = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        fec = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_xcliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_xMonto = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_xnumeroFactura = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jcb_xvendedor = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        JRFACTURAS = new javax.swing.JRadioButton();
        JRTICKETS = new javax.swing.JRadioButton();
        JRproformas = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btn_Eliminar = new javax.swing.JButton();
        btn_mostrarAll1 = new javax.swing.JButton();
        btn_excel = new javax.swing.JButton();
        btn_copiarFactura = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        buttonGroup1.add(JRFACTURAS);
        buttonGroup1.add(JRTICKETS);
        buttonGroup1.add(JRproformas);

        setClosable(true);
        setTitle("LISTA VENTAS");
        setMaximumSize(new java.awt.Dimension(1098, 696));
        setMinimumSize(new java.awt.Dimension(1098, 696));
        setPreferredSize(new java.awt.Dimension(1098, 696));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jdchoserdesde.setDateFormatString("yyyy-MM-dd");
        jdchoserdesde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jdchoserdesdeMouseClicked(evt);
            }
        });
        jPanel1.add(jdchoserdesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 190, -1));

        jdchoserhasta.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(jdchoserhasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 190, -1));

        jLabel4.setText("Desde:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel5.setText("Hasta:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        btn_hoy.setText("HOY");
        btn_hoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hoyActionPerformed(evt);
            }
        });
        jPanel1.add(btn_hoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 82, -1));

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 82, 38));
        jPanel1.add(fec, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 120, 30));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Buscar por Cliente");

        txt_xcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_xclienteActionPerformed(evt);
            }
        });
        txt_xcliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_xclienteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_xclienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_xclienteKeyTyped(evt);
            }
        });

        jLabel3.setText("Buscar por Monto");

        txt_xMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_xMontoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_xMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_xcliente))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_xcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_xMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 290, 110));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Buscar por Numero de Factura");

        txt_xnumeroFactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_xnumeroFacturaKeyReleased(evt);
            }
        });

        jLabel6.setText("Buscar por Vendedor");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jcb_xvendedor, 0, 231, Short.MAX_VALUE)
                    .addComponent(txt_xnumeroFactura))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_xnumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(5, 5, 5)
                .addComponent(jcb_xvendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 270, 110));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        JRFACTURAS.setSelected(true);
        JRFACTURAS.setText("FACTURAS");
        JRFACTURAS.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JRFACTURASItemStateChanged(evt);
            }
        });

        JRTICKETS.setText("TICKETS");
        JRTICKETS.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JRTICKETSItemStateChanged(evt);
            }
        });

        JRproformas.setText("PROFORMAS");
        JRproformas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JRproformasItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JRTICKETS)
                    .addComponent(JRFACTURAS)
                    .addComponent(JRproformas))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(JRFACTURAS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JRTICKETS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JRproformas)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(901, 10, 130, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 1040, 125);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Listar Productos"));
        jPanel2.setAutoscrolls(true);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setColumnSelectionAllowed(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 31, 1050, 360));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 145, 1070, 410);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(449, 824, 90, 24);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ShowAll.png"))); // NOI18N
        btn_Eliminar.setText("Mostrar Todo");
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MostrarTodoActionPerformed(evt);
            }
        });

        btn_mostrarAll1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/deleteUser.png"))); // NOI18N
        btn_mostrarAll1.setText("Eliminar");
        btn_mostrarAll1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });

        btn_excel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-MS Excel-48.png"))); // NOI18N
        btn_excel.setText("Excel");
        btn_excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excelActionPerformed(evt);
            }
        });

        btn_copiarFactura.setText("Copiar");
        btn_copiarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_copiarFacturaActionPerformed(evt);
            }
        });

        jButton1.setText("REIMPRIMIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Anular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Anular Y Copiar");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btn_mostrarAll1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_copiarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btn_excel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(192, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_mostrarAll1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_copiarFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_excel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6);
        jPanel6.setBounds(10, 570, 1060, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_xclienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_xclienteKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_xclienteKeyPressed

    private void ocultarFIlasJtable() {
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
        jTable1.getColumnModel().getColumn(1).setMaxWidth(100);
        jTable1.getColumnModel().getColumn(1).setMinWidth(100);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(2).setMaxWidth(160);
        jTable1.getColumnModel().getColumn(2).setMinWidth(160);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(160);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(110);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(160);
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(175);
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(150);
    }

    private void txt_xclienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_xclienteKeyReleased
        // TODO add your handling code here:
        ProductosDao obj = new ProductosDao();
        jTable1.setModel(obj.Buscar_table("Producto", txt_xcliente.getText()));
        this.ocultarFIlasJtable();///

    }//GEN-LAST:event_txt_xclienteKeyReleased

    private void txt_xnumeroFacturaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_xnumeroFacturaKeyReleased
        // TODO add your handling code here:
        ProductosDao obj = new ProductosDao();
        jTable1.setModel(obj.Buscar_table("codigoAlterno", txt_xnumeroFactura.getText()));
        this.ocultarFIlasJtable();
        ///
    }//GEN-LAST:event_txt_xnumeroFacturaKeyReleased

    private void txt_xMontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_xMontoKeyReleased
        // TODO add your handling code here:
        ProductosDao obj = new ProductosDao();
        jTable1.setModel(obj.Buscar_table("codigoBarras", txt_xMonto.getText()));
        this.ocultarFIlasJtable();
        ///
    }//GEN-LAST:event_txt_xMontoKeyReleased

    private Integer llenarjcbSelectedItemMarca(String name) {
        Integer codigo_Mrca = null;
        //Productos onj = new Productos();
        MarcasDao objDao = new MarcasDao();
        ArrayList<Marcas> lista = new ArrayList<Marcas>();
        lista = (ArrayList<Marcas>) objDao.listar();
        for (Marcas marca1 : lista) {
            if (marca1.getMarca().equals(name)) {
                codigo_Mrca = marca1.getCodigo();
                Object ob;
                ob = name;
                //Crear_Usuarios.jcb_tipo.setSelectedItem(0);
                Crear_Productos.setItemSelectMarcas = ob;

                //    System.out.println("Vista.Usuarios.Buscar_usuarios.llenarjcbSelectedItem()" + tipo_Usuario.getTipo());
            }

        }

        return codigo_Mrca;
    }

    private Integer llenarjcbSelectedItemModelo(String name) {
        Integer codigo_Modelo = null;
        //Productos onj = new Productos();
        ModelosDao objDao = new ModelosDao();
        ArrayList<Modelos> lista = new ArrayList<Modelos>();
        lista = (ArrayList<Modelos>) objDao.listar();
        for (Modelos obj2 : lista) {
            if (obj2.getModelo().equals(name)) {
                codigo_Modelo = obj2.getCodigo();
                Object ob;
                ob = name;
                //Crear_Usuarios.jcb_tipo.setSelectedItem(0);
                Crear_Productos.setItemSelectModelo = ob;

                //  System.out.println("Vista.Usuarios.Buscar_usuarios.llenarjcbSelectedItem()" + mode.getTipo());
            }

        }

        return codigo_Modelo;
    }

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        JTable table = (JTable) evt.getSource();
        clicJtable = 1;
        this.modelo = (DefaultTableModel) jTable1.getModel();
        int row = jTable1.getSelectedRow();
        rowSeleccionadaJTable = row;
//////////////        int col = jTable1.getSelectedColumn();
//////////////        modelo = (DefaultTableModel) jTable1.getModel();
//////////////        System.out.println("row: " + row);
//////////////        System.out.println("col: " + col);
        Integer codigoSeleccionado = Integer.parseInt(modelo.getValueAt(row, 0).toString());
//////////////        System.out.println("Vista.Usuarios.BuscarFacturas.jTable1MouseClicked()codiggo>:" + modelo.getValueAt(row, 0));
//////////////        // System.out.println("Vista.Usuarios.BuscarFacturas.jTable1MouseClicked()codigo seleccionado: "+cofigoFactSeleccionado);

        FacturasDao facDao = new FacturasDao();
        facturas1 = facDao.buscarConID(codigoSeleccionado);

        if (evt.getButton() == MouseEvent.BUTTON1) {
            System.out.println("BOTON 1");
            System.out.println("Vista.Usuarios.BuscarFacturas.jTable1MouseClicked()secuecnaia  :" + modelo.getValueAt(row, 2).toString());
            // operacionFacturauPDATEandAddRowrs();
        }
        if (evt.getButton() == MouseEvent.BUTTON2) {
            System.out.println("BOTON 2");
        }
        if (evt.getButton() == MouseEvent.BUTTON3) {
            System.out.println("BOTON 3");
        }
        try {
            System.out.println("Vista.Usuarios.BuscarFacturas.jTable1MouseClicked()secuecnaia  :" + modelo.getValueAt(row, 2).toString());
            if (jTable1.getSelectedRow() != -1) {
                // remove selected row from the model
                if (jTable1.getRowCount() > 0) {
                    if (evt.getClickCount() == 2) {

                        //String rutaInforme = "C:\\Users\\USUARIO\\OneDrive\\NetBeansProjects\\Sofi\\src\\Reportes\\FACTURA.jasper";
                        //String rutaInforme = Ejemplo.factura1;
                        String rutaInforme = Ejemplo.factura2;
                        Map parametros = new HashMap();
                        parametros.put("numeroFactura", modelo.getValueAt(row, 2).toString());
                        System.out.println("Vista.Usuarios.BuscarFacturas.jTable1MouseClicked()secuecnaia  :" + modelo.getValueAt(row, 2).toString());

                        ImpresionDao imp = new ImpresionDao();
                        imp.getShowReport(parametros, rutaInforme);

                    }
                    if (evt.getClickCount() == 1) {
                        secfacturareimpprimr = modelo.getValueAt(row, 2).toString();

                    }

                }
            }

        } catch (Exception e) {
            msg.setMensaje(e.toString());
        }

        if (evt.getClickCount() == 2) {
//llenasmos JCBOX marcas        
            Marcas obj = new Marcas();
            MarcasDao a = new MarcasDao();
//            obj = a.buscarConID(usuario.getModelos_marcas_codigo());
            Crear_Productos.setItemSelectMarcas = obj.getMarca();
            //this.llenarjcbSelectedItemMarca(obj.getMarca());
//llenasmos JCBOX Modelos
            Modelos objm = new Modelos();
            ModelosDao abjmDao = new ModelosDao();
            //          objm = abjmDao.buscarConID(usuario.getModelo_codigo());
            Crear_Productos.setItemSelectModelo = objm.getModelo();
            //this.llenarjcbSelectedItemMarca(objm.getModelo());

            // obj_crea.jButton1.setName("Actualizar");
            //        obj_crea.jButton1.setText("Actualizar");
            //      Principal.desktopPane.add(obj_crea);
            //    obj_crea.setVisible(true);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void txt_xclienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_xclienteKeyTyped
        // TODO add your handling code here:
//        ValidaNUmeros val = new ValidaNUmeros();
//        val.keyTyped(evt);
    }//GEN-LAST:event_txt_xclienteKeyTyped

    private void btn_excelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excelActionPerformed
//        // TODO add your handling code here:
        Date date1 = new Date();
        Date date2 = new Date();
        String fechaInicio = HoraFecha.fecha_aa_mm_dd_HH_mm_ss(jdchoserdesde.getDate().toString());

        String fechaFIn = HoraFecha.fecha_aa_mm_dd_HH_mm_ss(jdchoserhasta.getDate().toString());

        //String rutaInforme = "C:\\Users\\USUARIO\\OneDrive\\NetBeansProjects\\Sofi\\src\\Reportes\\report1.jasper";
        String rutaInforme = Ejemplo.listaComprasFilepdf;
        Map parametros = new HashMap();
        java.util.Date utilDate1 = new java.util.Date();
        java.util.Date utilDate2 = new java.util.Date();
        utilDate1 = jdchoserdesde.getDate();
        utilDate2 = jdchoserhasta.getDate();
        java.sql.Timestamp a = new java.sql.Timestamp(utilDate1.getTime());
        java.sql.Timestamp b = new java.sql.Timestamp(utilDate2.getTime());

        parametros.put("s1", a);
        parametros.put("s2", b);
        //JOptionPane.showConfirmDialog(rootPane, a +"--"+b);
        ImpresionDao imp = new ImpresionDao();
        imp.impresionShowReport(parametros, rutaInforme);
//        Thread t = new Thread() {
//
//            public void run() {
//                XSSFWorkbook workbook = new XSSFWorkbook();
//                XSSFSheet hoja = workbook.createSheet();
//                XSSFRow fila = hoja.createRow(0);
//
//                fila.createCell(0).setCellValue("Cedula");
//                fila.setHeightInPoints(23);
//                fila.createCell(1).setCellValue("Nombres");
//                fila.createCell(2).setCellValue("Direccion");
//
//                Principal.jProgressBar2.setMaximum(jTable1.getRowCount());
//                XSSFRow filas;
//                Principal.jProgressBar2.setStringPainted(true);
//
//                for (int i = 0; i < jTable1.getRowCount(); i++) {
//                    jTable1.setRowSelectionInterval(i, i);
//
//                    Principal.jProgressBar2.setValue(i + 1);
//                    filas = hoja.createRow(i + 1);
//                    filas.createCell(0).setCellValue(jTable1.getValueAt(i, 0).toString());
//                    filas.createCell(1).setCellValue(jTable1.getValueAt(i, 1).toString());
//                    filas.createCell(2).setCellValue(jTable1.getValueAt(i, 2).toString());
//
//                    Principal.jProgressBar2.setString("Esxportando Usuarios del Sistema a Excel...");
//                    try {
//                        Thread.sleep(20);
//                    } catch (InterruptedException ex) {
//                        Logger.getLogger(Buscar_usuarios.class.getName()).log(Level.SEVERE, null, ex);
//                    }
//                }
//                Principal.jProgressBar2.setValue(0);
//                Principal.jProgressBar2.setString("");
//
//                try {
//
//                    workbook.write(new FileOutputStream(new File("D:\\Excel.xlsx")));
//
//                } catch (Exception e) {
//                }
//
//            }
//        ;
//
//        };
//        t.start();

////        if (jTable1.getRowCount() < 0) {
////            JFileChooser chooser = new JFileChooser();
////            FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de excel", "xls");
////            chooser.setFileFilter(filter);
////            chooser.setDialogTitle("Guardar archivo");
////            chooser.setAcceptAllFileFilterUsed(false);
////            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
////                List<JTable> tb = new ArrayList();
////                List<String> nom = new ArrayList();
////                tb.add(jTable1);
////                nom.add("Compras por factura");
////                String file = chooser.getSelectedFile().toString().concat(".xls");
////                try {
////                    Exporter e = new Exporter(new File(file), tb, nom);
////
////                    if (e.export()) {
////                        JOptionPane.showMessageDialog(null, "Los datos fueron exportados a excel en el directorio seleccionado", "Mensaje de Informacion", JOptionPane.INFORMATION_MESSAGE);
////                    }
////                } catch (Exception e) {
////                    JOptionPane.showMessageDialog(null, "Hubo un error " + e.getMessage(), " Error", JOptionPane.ERROR_MESSAGE);
////                }
////            }
////        } else {
////            JOptionPane.showMessageDialog(this, "No hay datos para exportar", "Mensaje de error", JOptionPane.ERROR_MESSAGE);
////        }
    }//GEN-LAST:event_btn_excelActionPerformed

    private void btn_MostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MostrarTodoActionPerformed
        // TODO add your handling code here:
        ProductosDao objDao = new ProductosDao();

        jTable1.setModel(objDao.Buscar_table_only_Activos());
        this.ocultarFIlasJtable();
        ///
    }//GEN-LAST:event_btn_MostrarTodoActionPerformed

    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed
        // TODO add your handling code here:
        if (!facturas1.getSecuencia().equals("")) {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "Confirmar la Eliminacion de la Factura numero: " + facturas1.getSecuencia(), "Eliminar Factura", dialogButton);
            if (dialogResult == 0) {
                FacturasDao obj1 = new FacturasDao();
                try {
                    if (clicJtable == 1) {
                        obj1.eliminar(facturas1);
                        setFechayHoraActualJDChooser();
                        FacturasDao obj = new FacturasDao();
                        String fechaInicio = HoraFecha.fecha_aa_mm_dd_HH_mm_ss(jdchoserdesde.getDate().toString());
                        String fechaFIn = HoraFecha.fecha_aa_mm_dd_HH_mm_ss(jdchoserhasta.getDate().toString());
                        jTable1.setModel(obj.listarFacturasTbModel(fechaInicio, fechaFIn, tipo_doc_seleccionado));
                        this.ocultarFIlasJtable();

                    }
                } catch (Exception ex) {
                    Logger.getLogger(Buscar_usuarios.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {

            }
        }
    }//GEN-LAST:event_btn_EliminarActionPerformed

    private void txt_xclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_xclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_xclienteActionPerformed

    private void btn_hoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hoyActionPerformed
        // TODO add your handling code here:
        setFechayHoraActualJDChooser();
        FacturasDao obj = new FacturasDao();
        String fechaInicio = HoraFecha.fecha_aa_mm_dd_HH_mm_ss(jdchoserdesde.getDate().toString());
        String fechaFIn = HoraFecha.fecha_aa_mm_dd_HH_mm_ss(jdchoserhasta.getDate().toString());
        jTable1.setModel(obj.listarFacturasTbModel(fechaInicio, fechaFIn, tipo_doc_seleccionado));
        this.ocultarFIlasJtable();

    }//GEN-LAST:event_btn_hoyActionPerformed

    private void jdchoserdesdeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdchoserdesdeMouseClicked
        // TODO add your handling code here:
        //jdchoserdesde
    }//GEN-LAST:event_jdchoserdesdeMouseClicked

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
        if (jdchoserdesde.getDate().before(jdchoserhasta.getDate())) {

            FacturasDao obj = new FacturasDao();
            String fechaInicio = HoraFecha.fecha_aa_mm_dd_HH_mm_ss(jdchoserdesde.getDate().toString());
            String fechaFIn = HoraFecha.fecha_aa_mm_dd_HH_mm_ss(jdchoserhasta.getDate().toString());
            jTable1.setModel(obj.listarFacturasTbModel(fechaInicio, fechaFIn, tipo_doc_seleccionado));
            this.ocultarFIlasJtable();
        } else {
            msg.setProgressBar(3000, "Ranngo Errado!! Fecha de Inicio es Mayor a la del Final...");
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:

    }//GEN-LAST:event_formInternalFrameClosed

    private void btn_copiarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_copiarFacturaActionPerformed
        // TODO add your handling code here:
        if (rowSeleccionadaJTable == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione Una Factura");
        } else {
            DefaultTableModel modelonow = new DefaultTableModel();
            Integer codigoFac = Integer.parseInt(jTable1.getValueAt(rowSeleccionadaJTable, 0).toString());
            FacturasDao fdao = new FacturasDao();
            Facturas fac = new Facturas();
            DetalleFactura detFac = new DetalleFactura();
            ClientesDao cdao = new ClientesDao();
            Clientes cli = new Clientes();
            fac = fdao.buscarConID(codigoFac);
            cli = cdao.buscarConID(fac.getClientes_codigo());

            String[] titulos
                    = {"costo", "#", "Codigo", "ARTICULO", "CANTIDAD",
                        "DESCUENTO", "BODEGA",
                        "P. UNIT", "P. TOTAL", "CANTIDAD"};

            
            
            modelonow = new DefaultTableModel(null, titulos) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    // make read only fields except column 0,13,14
                    return column == 3 || column == 4 || column == 5 || column == 7;
                    //  return false;
                }
            };

            // Crear_Facturas.jTable1.setModel(modelo);
            Crear_Facturas cf = new Crear_Facturas();
            cf.txt_cedula.setText(cli.getCedula());
            if (cli.getCelular().equalsIgnoreCase("")) {
                cf.txt_celular.setText(cli.getTelefono());
            } else {
                cf.txt_celular.setText(cli.getCelular() + "-" + cli.getTelefono());
            }
            cf.txt_celular.setText(cli.getCelular());
            cf.txt_dir.setText(cli.getDireccion());
            cf.txt_nombres.setText(cli.getNombre());
            cf.txt_sec1.setText(fac.getEstablecimiento());
            cf.txt_sec2.setText(fac.getPtoEmision());
            cf.txt_secNUmFac.setText(fac.getSecfactura());
            cf.txt_total_val_grande.setText(fac.getTotal());
            cf.txt_subtotal_val.setText(fac.getSubtotaI_con_iva());
            cf.txt_subtotalIvaValor_conIva12.setText(fac.getSubtotaI_con_iva());
            cf.txt_subtotalIvaValorCero0.setText(fac.getSubtotal_sin_iva());
            cf.txt_total_vAL_PEQ.setText(fac.getTotal());
            cf.txt_descuentoGenral.setText(fac.getDescuento());
            cf.txt_usuarioCodigo.setText(fac.getUsuarios_Codigo().toString());
            cf.txt_utilidad.setText(fac.getUtilidad());
            cf.utilidad=Double.parseDouble(fac.getUtilidad());          
            
            if (fac.getTipo_documento().equalsIgnoreCase("FACTURA")) {
            }
            cf.check_Fac.setSelected(true);
            if (fac.getTipo_documento().equalsIgnoreCase("ticket")) {
                cf.check_tikets.setSelected(true);
            }
            if (fac.getTipo_documento().equalsIgnoreCase("proforma")) {
                cf.check_proformas.setSelected(true);
            }
////////////
            DetalleFacturaDao detFacdao = new DetalleFacturaDao();

         
            cf.setModeloColumnas(cf.jTable1);
     ///     modelonow = detFacdao.getDetalleFacutraByIdFactura(codigoFac);
            
            cf.jTable1.setModel(modelonow);
         //   cf.modelo=(DefaultTableModel) cf.jTable1.getModel();
            // cf.jTable1.setModel(modelonow);
            desktopPane.add(cf);
            cf.setVisible(true);
            System.out.println("CLiente: " + fac.getUsuarios_Codigo());
        }

    }//GEN-LAST:event_btn_copiarFacturaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (Principal.facturatiriiasoGrande.equalsIgnoreCase("ROLLO")) {
            ImpresionDao impdao = new ImpresionDao();
            impdao.impresionEnTirillasFaturas(secfacturareimpprimr);
        } else {
            HashMap parametros = new HashMap();
            String template = Variables.DIR_REPORTE_FACTURA;

            System.out.println("Ruta Archivo: " + template);
            parametros.put("numeroFactura", secfacturareimpprimr);
            ImpresionDao imp = new ImpresionDao();
            //imp.getShowReport(parametros, rutaInforme);
            ///imp.ExportPDF(parametros, rutaInforme);
            imp.impresionDontShowReport(parametros, template);
            // imp.impresionDontShowReport(parametros, rutaInforme);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void JRFACTURASItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JRFACTURASItemStateChanged
        // TODO add your handling code here:
        if (JRFACTURAS.isSelected()) {
            tipo_doc_seleccionado = "FACTURA";
            llenarjtable();
        }

    }//GEN-LAST:event_JRFACTURASItemStateChanged

    private void JRTICKETSItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JRTICKETSItemStateChanged
        // TODO add your handling code here:
        if (JRTICKETS.isSelected()) {
            tipo_doc_seleccionado = "TICKET";
            llenarjtable();
        }
    }//GEN-LAST:event_JRTICKETSItemStateChanged

    private void JRproformasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JRproformasItemStateChanged
        // TODO add your handling code here:
        if (JRproformas.isSelected()) {
            tipo_doc_seleccionado = "PROFORMA";
            llenarjtable();
        }
    }//GEN-LAST:event_JRproformasItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (rowSeleccionadaJTable == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione Una Factura");
        } else {
            Integer codigoFac = Integer.parseInt(jTable1.getValueAt(rowSeleccionadaJTable, 0).toString());
            FacturasDao fdao = new FacturasDao();
            if (fdao.UpdateAnuladoComprobantedeVenta(codigoFac)) {
                codigoFac = null;
                if (jdchoserdesde.getDate().before(jdchoserhasta.getDate())) {

                    FacturasDao obj = new FacturasDao();
                    String fechaInicio = HoraFecha.fecha_aa_mm_dd_HH_mm_ss(jdchoserdesde.getDate().toString());
                    String fechaFIn = HoraFecha.fecha_aa_mm_dd_HH_mm_ss(jdchoserhasta.getDate().toString());
                    jTable1.setModel(obj.listarFacturasTbModel(fechaInicio, fechaFIn, tipo_doc_seleccionado));
                    this.ocultarFIlasJtable();
                } else {
                    msg.setProgressBar(3000, "Ranngo Errado!! Fecha de Inicio es Mayor a la del Final...");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Error al intenta anular " + tipo_doc_seleccionado);
            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JRFACTURAS;
    private javax.swing.JRadioButton JRTICKETS;
    private javax.swing.JRadioButton JRproformas;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_copiarFactura;
    private javax.swing.JButton btn_excel;
    private javax.swing.JButton btn_hoy;
    private javax.swing.JButton btn_mostrarAll1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel fec;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jcb_xvendedor;
    private com.toedter.calendar.JDateChooser jdchoserdesde;
    private com.toedter.calendar.JDateChooser jdchoserhasta;
    private javax.swing.JTextField txt_xMonto;
    private javax.swing.JTextField txt_xcliente;
    private javax.swing.JTextField txt_xnumeroFactura;
    // End of variables declaration//GEN-END:variables

}
