/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Usuarios;

import ClasesAuxiliares.Exporter;
import Controlador.Usuarios.Tipo_UsuariosDao;
import Controlador.Usuarios.UsuariosDao;
import Modelo.Tipo_Usuario;
import Modelo.Usuarios;
import Vista.Principal;
import Vlidaciones.ValidaNUmeros;
import java.awt.Color;
import java.awt.Font;
import java.awt.Point;
import java.awt.Rectangle;
import java.beans.PropertyVetoException;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.Context;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.text.StyleContext;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author USUARIO
 */
public class Buscar_Tipos extends javax.swing.JInternalFrame {

    /**
     * Creates new form FBUsuarios
     */
    Integer clicJtable = 0;
    Tipo_Usuario obj_ = new Tipo_Usuario();
    String sql_all = "select * from Tipos_usuarios";
 public static Integer indexPositiotoolBar;
    //CUsuarios obj = new CUsuarios();
    public Buscar_Tipos() {

        initComponents();

        Tipo_UsuariosDao obj = new Tipo_UsuariosDao();
      
        jTable1.setModel(obj.Buscar_table_only_Activos());
        this.ocultarFIlasJtable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_tipo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_Eliminar = new javax.swing.JButton();
        btn_mostrarAll1 = new javax.swing.JButton();
        btn_excel = new javax.swing.JButton();

        setClosable(true);
        setTitle("BUscar Tipos de Usuario");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_tipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_tipoKeyReleased(evt);
            }
        });

        jLabel2.setText("Tipo de Usuario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setColumnSelectionAllowed(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 104, 860, -1));

        btn_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ShowAll.png"))); // NOI18N
        btn_Eliminar.setText("Mostrar Todo");
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, 180, 50));

        btn_mostrarAll1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/deleteUser.png"))); // NOI18N
        btn_mostrarAll1.setText("Eliminar");
        btn_mostrarAll1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarAll1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_mostrarAll1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 160, 50));

        btn_excel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-MS Excel-48.png"))); // NOI18N
        btn_excel.setText("Excel");
        btn_excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excelActionPerformed(evt);
            }
        });
        getContentPane().add(btn_excel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, 170, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ocultarFIlasJtable() {

        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
//        jTable1.getColumnModel().getColumn(7).setMaxWidth(0);
//        jTable1.getColumnModel().getColumn(7).setMinWidth(0);
//        jTable1.getColumnModel().getColumn(7).setPreferredWidth(0);

    }

    private void txt_tipoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tipoKeyReleased
        // TODO add your handling code here:
        Tipo_UsuariosDao obj = new Tipo_UsuariosDao();
        jTable1.setModel(obj.Buscar_table("Tipo", txt_tipo.getText()));
        this.ocultarFIlasJtable();
        ///
    }//GEN-LAST:event_txt_tipoKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        clicJtable = 1;
        //Double clicked
        Tipo_Usuario obj = new Tipo_Usuario();
        Tipo_UsuariosDao  objDao = new Tipo_UsuariosDao();
        Crear_Tipo_Usuarios obj_crea = new Crear_Tipo_Usuarios();

        JTable table = (JTable) evt.getSource();
        int row = table.getSelectedRow();
        int col = table.getSelectedColumn();
        //obtengo el codigo del usuario
        String Valor = table.getValueAt(row, 0).toString();
        //mando a buscar la informacion del usuaruio con el codigo obtenido dle evento click
        obj= objDao.buscarConID(Integer.parseInt(Valor));
        obj_ = obj;
        //lleno el fomulario 
        obj_crea.txt_codigo.setText(String.valueOf(obj.getCodigo()));
        obj_crea.txt_tipo.setText(obj.getTipo());
        obj_crea.txt_descripcion.setText(obj.getDescripcion());
        if (evt.getClickCount() == 2) {
            obj_crea.jButton1.setName("Actualizar");
            obj_crea.jButton1.setText("Actualizar");
            Principal.desktopPane.add(obj_crea);
            obj_crea.setVisible(true);

        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_excelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excelActionPerformed
        // TODO add your handling code here:
        Thread t = new Thread() {

            public void run() {
                XSSFWorkbook workbook = new XSSFWorkbook();
                XSSFSheet hoja = workbook.createSheet();
                XSSFRow fila = hoja.createRow(0);

                fila.createCell(0).setCellValue("Tipo");
                fila.setHeightInPoints(23);
                fila.createCell(1).setCellValue("DESCRIPCION");

                Principal.jProgressBar2.setMaximum(jTable1.getRowCount());
                XSSFRow filas;
                Principal.jProgressBar2.setStringPainted(true);

                for (int i = 0; i < jTable1.getRowCount(); i++) {
                    jTable1.setRowSelectionInterval(i, i);

                    Principal.jProgressBar2.setValue(i + 1);
                    filas = hoja.createRow(i + 1);
                    filas.createCell(0).setCellValue(jTable1.getValueAt(i, 0).toString());
                    filas.createCell(1).setCellValue(jTable1.getValueAt(i, 1).toString());

                    Principal.jProgressBar2.setString("Esxportando Tipos de Usuarios del Sistema a Excel...");
                    try {
                        Thread.sleep(20);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Buscar_Tipos.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                Principal.jProgressBar2.setValue(0);
                Principal.jProgressBar2.setString("");

                try {

                    workbook.write(new FileOutputStream(new File("D:\\Reporte_tipos_Usuarios.xlsx")));

                } catch (Exception e) {
                }

            }
        ;

        };
        t.start();

    }//GEN-LAST:event_btn_excelActionPerformed

    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed
        // TODO add your handling code here:
        Tipo_UsuariosDao obj = new Tipo_UsuariosDao();
        //String sql = "select * from usuarios";
        DefaultTableModel modelo = null;

        String[] titulos
                = {"Codigo", "Tipo", "Descripcion"};
        String[] registros = new String[3];
        modelo = new DefaultTableModel(null, titulos) {

            @Override
            public boolean isCellEditable(int row, int column) {
                // make read only fields except column 0,13,14
                //  return column == 0 || column == 13 || column == 14;
                return false;
            }
        };

        ResultSet rs = obj.listar_table(sql_all);
        try {

            while (rs.next()) {

                registros[0] = String.valueOf(rs.getInt("Codigo"));
                registros[1] = String.valueOf(rs.getString("Tipo"));
                registros[2] = rs.getString("Descripcion");
                modelo.addRow(registros);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Buscar_Tipos.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTable1.setModel(modelo);
        
        
        //oculta la columna CERO,  q es la que contiene el codido del elemnto pk
        this.ocultarFIlasJtable();
        ///
    }//GEN-LAST:event_btn_EliminarActionPerformed

    private void btn_mostrarAll1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarAll1ActionPerformed
        // TODO add your handling code here:
        Tipo_UsuariosDao obj1Dao = new Tipo_UsuariosDao();
        try {
            if (clicJtable == 1) {
                obj1Dao.eliminar(obj_);
                Tipo_UsuariosDao obj = new Tipo_UsuariosDao();

                jTable1.setModel(obj.Buscar_table_only_Activos());
                this.ocultarFIlasJtable();
            }
        } catch (Exception ex) {
            Logger.getLogger(Buscar_Tipos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_mostrarAll1ActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formInternalFrameClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JButton btn_excel;
    private javax.swing.JButton btn_mostrarAll1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_tipo;
    // End of variables declaration//GEN-END:variables

}
