/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Usuarios;

import ClasesAuxiliares.Leertxt;
import ClasesAuxiliares.NewSql.Forms.OperacionesForms;
import ClasesAuxiliares.http.ConsultaCedulas;
import Controlador.Coneccion;
import ClasesAuxiliares.debug.Deb;
import ClasesAuxiliares.tablas.SetRenderJTableCXC;
import Controlador.Usuarios.ClientesDao;
import Controlador.Usuarios.FormasPagoCVDao;
import Modelo.Clientes;
import Modelo.FormasPagoCV;
import Modelo.Tipo_Usuario;
import Modelo.Usuarios;
import Vista.Dialogs.PagoConCheque;
import Vista.Principal;
import Vista.Sat.Crear_Orden;
import Vlidaciones.ProgressBar;
import Vlidaciones.VaciarTexto;
import Vlidaciones.ValidaCedula;
import Vlidaciones.ValidaEmail;
import Vlidaciones.ValidaNUmeros;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.math.BigInteger;
import java.sql.Connection;
import java.sql.Date;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import org.json.JSONObject;

/**
 *
 * @author USUARIO
 */
public class Crear_Clientes extends javax.swing.JInternalFrame {

    public static boolean isLlamadoDesdeNuevoAparato = false;
    public static boolean isllamadoDesdePagoConChque = false;
    public static boolean isllamadoDesdeRegistroMasivoCOmprasSRI = false;
    public static boolean isllamadoDesdeNuevoProveedor = false;

    private ArrayList<FormasPagoCV> listaFormasPago = new ArrayList<>();
    private FormasPagoCV formaPagoSeleccionada = new FormasPagoCV();
    private FormasPagoCVDao fpDao = new FormasPagoCVDao();

    public static Integer indexPositiotoolBar;
    ValidaEmail obj_valida_email = new ValidaEmail();

    public static Integer buscarProvvedoroCLiente = 0; //0 cliente - 1 proveedor

    /**
     * Creates new form FCUsuarios
     */
    public Crear_Clientes() {
        initComponents();

        OperacionesForms.inicializarJtextFieldMyusculas(txt_observaciones);
        OperacionesForms.inicializarJtextFieldMyusculas(txt_ciudad);
        OperacionesForms.inicializarJtextFieldMyusculas(txt_dir);
        OperacionesForms.inicializarJtextFieldMyusculas(txt_nombreComercia);
        OperacionesForms.inicializarJtextFieldMyusculas(txt_nombres);
        OperacionesForms.inicializarJtextFieldMyusculas(txt_provincia);

        OperacionesForms.setbuttonsAceptarCancelar(jButton1, jButton2);
        if (isllamadoDesdeNuevoProveedor) {
            buscarProvvedoroCLiente = 1;
        } else {
            buscarProvvedoroCLiente = 0;
        }
        listaFormasPago = fpDao.listarFormaPagoVentas();
        for (FormasPagoCV f : listaFormasPago) {
            jcb_FormaPagoPredeterminada.addItem(f.getFormaPago().toString());
            if (f.getFormaPago().equalsIgnoreCase(OperacionesForms._EFECTIVO_TEXT)) {
                jcb_FormaPagoPredeterminada.setSelectedItem(f.getFormaPago());
            } else {
                jcb_FormaPagoPredeterminada.setSelectedItem(OperacionesForms._COMBO_SELECCIONE_TEXT);
            }
//        JRootPane rootPane = SwingUtilities.getRootPane(this.jButton1);
//        rootPane.setDefaultButton(this.jButton1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_codigo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txt_ciudad = new javax.swing.JTextField();
        txt_provincia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_genero = new javax.swing.JTextField();
        txt_estadoCivil = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_huella = new javax.swing.JTextField();
        txt_nacionalidad = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_dir = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_mail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        txt_celular = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_nombres = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFechaNaciomiento = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_nombreComercia = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txt_cedulax = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_observaciones = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jcb_FormaPagoPredeterminada = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jcb_tipoCLiente = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Nuevo Cliente");
        setToolTipText("");
        setVisible(false);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txt_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, 130, 30));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de eUsuario"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Adicionales"));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(txt_ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 54, 288, -1));
        jPanel6.add(txt_provincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 25, 288, -1));

        jLabel1.setText("Provincia");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 28, -1, -1));

        jLabel2.setText("Ciudad");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 57, -1, -1));

        jLabel14.setText("Genero");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 92, -1, -1));
        jPanel6.add(txt_genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 89, 41, -1));
        jPanel6.add(txt_estadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 122, 67, -1));

        jLabel11.setText("Estado Civil");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 125, -1, -1));

        jLabel16.setText("Huella");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 92, -1, -1));
        jPanel6.add(txt_huella, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 89, 162, -1));

        txt_nacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nacionalidadActionPerformed(evt);
            }
        });
        jPanel6.add(txt_nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 122, 94, -1));

        jLabel15.setText("Nacionalidad");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 125, -1, -1));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 272, 371, 160));
        jPanel2.add(txt_dir, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 243, 354, -1));

        jLabel6.setText("Direccion");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 220, -1, -1));

        txt_mail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_mailKeyPressed(evt);
            }
        });
        jPanel2.add(txt_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 197, 354, -1));

        jLabel9.setText("Email");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 174, -1, -1));
        jPanel2.add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 145, 110, -1));
        jPanel2.add(txt_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 145, 149, -1));

        jLabel8.setText("Celular");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 122, 67, -1));

        jLabel7.setText("Convencional");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 122, 88, -1));
        jPanel2.add(txt_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 93, 354, -1));

        jLabel5.setText("Nombres(*)");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 70, -1, -1));

        txtFechaNaciomiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaNaciomientoActionPerformed(evt);
            }
        });
        jPanel2.add(txtFechaNaciomiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 145, 84, -1));

        jLabel13.setText("Fech. Nac.");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        jLabel17.setText("Nombre Comercial");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        txt_nombreComercia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nombreComerciaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreComerciaKeyTyped(evt);
            }
        });
        jPanel2.add(txt_nombreComercia, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 220, -1));

        txt_cedulax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cedulaxFocusGained(evt);
            }
        });
        txt_cedulax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cedulaxActionPerformed(evt);
            }
        });
        txt_cedulax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cedulaxKeyPressed(evt);
            }
        });

        jLabel4.setText("Cedula(*)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_cedulax, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_cedulax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 140, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 390, 440));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Observaciones"));

        txt_observaciones.setColumns(20);
        txt_observaciones.setRows(5);
        jScrollPane1.setViewportView(txt_observaciones);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 370, -1));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Foto"));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 350, 300));

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setBackground(new java.awt.Color(102, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Crear Clientes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jButton1PropertyChange(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jcb_FormaPagoPredeterminada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE" }));
        jcb_FormaPagoPredeterminada.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcb_FormaPagoPredeterminadaItemStateChanged(evt);
            }
        });
        jcb_FormaPagoPredeterminada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_FormaPagoPredeterminadaActionPerformed(evt);
            }
        });

        jLabel10.setText("Forma de Pago");

        jcb_tipoCLiente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INACTIVO" }));
        jcb_tipoCLiente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcb_tipoCLienteItemStateChanged(evt);
            }
        });

        jLabel3.setText("Tipo Cliente");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcb_FormaPagoPredeterminada, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jcb_tipoCLiente, 0, 197, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel3))
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_FormaPagoPredeterminada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_tipoCLiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 760, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_mailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_mailKeyPressed

        if (obj_valida_email.validaEmail(txt_mail.getText())) {
            txt_mail.setBackground(Color.white);
        } else {
            txt_mail.setBackground(Color.cyan);
        }
    }//GEN-LAST:event_txt_mailKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ClientesDao obj = new ClientesDao();
        Clientes u = new Clientes();
        // Object objcb_tipo = jcb_tipo.getSelectedItem();
        // Object objcb_estado = jcb_estado.getSelectedItem();

        if (!txt_cedulax.getText().isEmpty() && !txt_nombres.getText().isEmpty()) {

            u.setCedula(txt_cedulax.getText());
            u.setNombre(txt_nombres.getText());
            u.setTelefono(txt_telefono.getText());
            u.setCelular(txt_celular.getText());
            u.setMail(txt_mail.getText());
            u.setDireccion(txt_dir.getText());
            u.setProvincia(txt_provincia.getText());
            u.setCiudad(txt_ciudad.getText());
            u.setNacionalidad(txt_nacionalidad.getText());
            u.setPagoPredeterminado(1);
            u.setEstadoCivil(txt_estadoCivil.getText());
            u.setGenereo(txt_genero.getText());
            u.setHuella(txt_huella.getText());
            u.setPagoPredeterminado(formaPagoSeleccionada.getCodigo());
//            long d = tarea.getFecha().getTime();
//            java.sql.Date fecha = new java.sql.Date(d);
            u.setNacimiento(txtFechaNaciomiento.getText());
            if (isllamadoDesdeNuevoProveedor) {
                u.setProveedor(1);
            } else {
                u.setProveedor(0);
            }
            if (evt.getActionCommand().equals("Actualizar")) {
                Deb.consola("Vista.Usuarios.CrearUsuarios.jButton1ActionPerformed()DDDDXXXXXCODIGO: " + txt_codigo.getText());
                u.setCodigo(Integer.parseInt(txt_codigo.getText()));
                obj.modificar(u);
                if (isLlamadoDesdeNuevoAparato) {
                    Crear_Orden.txtRUC.setText(u.getCedula());
                    Crear_Orden.txtNombres.setText(u.getNombre());
                    Crear_Orden.newCliente = u;
                    this.dispose();
                }
                this.dispose();
                ClientesDao cu = new ClientesDao();
                String sql = "select * from Clientes  order BY Nombres ";

                Buscar_Clientes.jTable1.setModel(cu.Buscar_table_only_Activos(buscarProvvedoroCLiente));

            } else {

                Integer r = obj.guardar(u);
                if (isllamadoDesdeRegistroMasivoCOmprasSRI) {
                    if (r > 0) {
                    ClientesDao cdao = new ClientesDao();
                    Leertxt.listaClientes.clear();
                    Leertxt.listaClientes = cdao.buscarAllCLientes(1);
                    SetRenderJTableCXC rendcxc = new SetRenderJTableCXC(10);
                    RegistraComprasMasivamaente.jTable1.setDefaultRenderer(Object.class, rendcxc);
                    isllamadoDesdeRegistroMasivoCOmprasSRI=false;
                    }
                }

                if (isllamadoDesdePagoConChque) {
                    PagoConCheque.cliente = u;
                    PagoConCheque.txtCliente.setText(u.getNombre());

                    this.dispose();
                }
                if (isLlamadoDesdeNuevoAparato) {
                    Crear_Orden.newCliente = u;
                    Crear_Orden.txtRUC.setText(u.getCedula());
                    Crear_Orden.txtNombres.setText(u.getNombre());
                    this.dispose();
                }
            }

            VaciarTexto limpiar = new VaciarTexto();
            limpiar.limpiar_texto(jPanel2);

            Deb.consola("Vista.Usuarios.FUsuarios.jButton1ActionPerformed()");
            dispose();
        } else {
//ProgressBar a = new ProgressBar(1000, "LLenar los campos Obligatorios");
            ProgressBar.mostrarMensajeAzul("Debes LLenar los campos Obligatorios");

//        
//            JOptionPane.showMessageDialog(null, "Debes LLenar los campos Obligatorios",
//                    "Información", JOptionPane.CLOSED_OPTION);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed

    }//GEN-LAST:event_formInternalFrameClosed

    private void jcb_FormaPagoPredeterminadaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcb_FormaPagoPredeterminadaItemStateChanged
        // TODO add your handling code here:
        for (FormasPagoCV f : listaFormasPago) {
            if (f.getFormaPago().equalsIgnoreCase(OperacionesForms._EFECTIVO_TEXT)) {
                formaPagoSeleccionada = f;

            }
        }
    }//GEN-LAST:event_jcb_FormaPagoPredeterminadaItemStateChanged

    private void jButton1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jButton1PropertyChange
        // TODO add your handling code here:
        //if(evt.getPropertyName())
        if (jButton1.getText().equals("Actualizar")) {
            //jcb_estado.setSelectedItem("");
        }
        Deb.consola("Vista.Usuarios.Crear_Usuarios.jButton1Prop,,,,,,,,ertyChange()" + evt.getNewValue());
    }//GEN-LAST:event_jButton1PropertyChange
//
    private void jcb_FormaPagoPredeterminadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_FormaPagoPredeterminadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_FormaPagoPredeterminadaActionPerformed

    private void txtFechaNaciomientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaNaciomientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaNaciomientoActionPerformed

    private void txt_nacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nacionalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nacionalidadActionPerformed

    public static void llenarcamposSRI(String ruc) {
        HashMap<String, String> hm = new HashMap<String, String>();
        try {
            //   ConsultaCedulas.getInfoSheylaGetokok(ruc);
            //     myResponse = null;
            try {
                hm = ConsultaCedulas.getInfoSheylaGetokok(ruc);
                //    myResponse = ConsultaCedulas.getInfoRegistroCivil(ruc);

                txtFechaNaciomiento.setText(hm.get("fecha"));
                txt_dir.setText(hm.get("direccion"));
                txt_observaciones.setLineWrap(true);
                txt_observaciones.setWrapStyleWord(true);
                txt_observaciones.setColumns(45);
                txt_observaciones.append(hm.get("actividad"));

                //txtFechaNaciomiento.setText(myResponse.getString("dob"));
                //txt_nacionalidad.setText(myResponse.getString("nationality"));
                txt_nombres.setText(hm.get("nombre"));
                txt_ciudad.setText(hm.get("ciudad"));
                //txt_genero.setText(myResponse.getString("genre"));
                //txt_huella.setText(myResponse.getString("fingerprint"));
                //txt_estadoCivil.setText(myResponse.getString("civilstate"));
                txt_provincia.setText(hm.get("provincia"));
                // txt_cedula.setText(hm.get("cedula"));
                //  ok = false;
            } catch (Exception ex) {
                Logger.getLogger(Crear_Clientes.class.getName()).log(Level.SEVERE, null, ex);
            }
            // ok = false;
        } catch (Exception ex) {
            Logger.getLogger(Crear_Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public static boolean buscarOCrearNuevoCLiente(String ruc) {

        boolean existeCliente = false;
        Clientes c = new Clientes();
        c = null;
        ClientesDao cDao = new ClientesDao();

        c = cDao.buscarConCedulaLike(ruc, 0);
        if (c != null) {
            Deb.consola(" aaasdddd  :  " + c.getCedula());
        } else {
            Deb.consola(" es null  :  ");
        }

        if (c == null) {
            if (ruc.length() == 10) {
                boolean ok = false;

                ok = ValidaCedula.validaRUC(ruc);
                if (ok) {

                    llenarcamposSRI(ruc);
                    ok = false;

                }
            }

            if (ruc.length() == 13) {
                boolean ok = false;
                //ValidaCedula v = new ValidaCedula();
                //ok = v.isCedula(txt_cedula.getText());
                ok = ValidaCedula.validaRUC(ruc);
                if (ok) {
                    llenarcamposSRI(ruc);
                    ok = false;
                }
            }

        } else {
            if (isLlamadoDesdeNuevoAparato) {
                existeCliente = true;
                Crear_Orden.newCliente = c;
//                

            } else {
                txt_celular.setText(c.getCelular());
                txt_ciudad.setText(c.getCiudad());
                txt_codigo.setText(c.getCodigo().toString());
                txt_dir.setText(c.getDireccion());
                txt_estadoCivil.setText(c.getEstadoCivil());
                txt_genero.setText(c.getGenereo());
                txt_huella.setText(c.getHuella());
                txt_mail.setText(c.getMail());
                txt_nacionalidad.setText(c.getNacionalidad());
                txt_nombreComercia.setText(c.getNombre());
                txt_nombres.setText(c.getNombre());
                txt_observaciones.setText(c.getObservaciones());
                txt_provincia.setText(c.getProvincia());
                txt_telefono.setText(c.getTelefono());
                ProgressBar.mostrarMensajeAzul("El Cliente ya esta resgistrado  :) ..");

            }

        }
        return existeCliente;
    }

    public static boolean buscarOCrearNuevoCLientevERIFICA(String ruc) {
        boolean existeCliente = false;
        Clientes c = new Clientes();
        ClientesDao cDao = new ClientesDao();

        c = cDao.buscarConCedulaLike(ruc, buscarProvvedoroCLiente);
        if (c.getCedula() == null) {
            if (ruc.length() == 10) {
                boolean ok = false;

                ok = ValidaCedula.validaRUC(ruc);
                if (ok) {
                    JSONObject myResponse;
                    try {
                        ok = false;
                    } catch (Exception ex) {
                        Logger.getLogger(Crear_Clientes.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }

            if (ruc.length() == 13) {
                boolean ok = false;
                ok = ValidaCedula.validaRUC(ruc);
                if (ok) {
                    JSONObject myResponse;
                    try {
                    } catch (Exception ex) {
                        Logger.getLogger(Crear_Clientes.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }

        } else {
            if (isLlamadoDesdeNuevoAparato) {
                existeCliente = true;
                Crear_Orden.newCliente = c;

                //  txt_nacionalidad.setText(c.getNacionalidad());
            }

        }
        return existeCliente;
    }
    private void txt_nombreComerciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreComerciaKeyPressed
        // TODO add your handling code here:


    }//GEN-LAST:event_txt_nombreComerciaKeyPressed

    private void txt_nombreComerciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreComerciaKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_nombreComerciaKeyTyped

    private void jcb_tipoCLienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcb_tipoCLienteItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_tipoCLienteItemStateChanged

    private void txt_cedulaxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cedulaxKeyPressed
        // TODO add your handling code here:
        if ((evt.getKeyCode() == KeyEvent.VK_ENTER && txt_cedulax.getText().length() == 10) || (evt.getKeyCode() == KeyEvent.VK_ENTER && txt_cedulax.getText().length() == 13)) {
            VaciarTexto.limpiar_texto(jPanel2);
            VaciarTexto.limpiar_texto(jPanel6);
            VaciarTexto.limpiar_texto(jPanel7);
            txt_observaciones.setText("");
            buscarOCrearNuevoCLiente(txt_cedulax.getText());
        }

    }//GEN-LAST:event_txt_cedulaxKeyPressed

    private void txt_cedulaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cedulaxActionPerformed
        try {
            // TODO add your handling code here:
            //  ConsultaCedulas.getInfoSheylaGetokok(txt_cedula.getText());

        } catch (Exception ex) {
            Logger.getLogger(Crear_Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txt_cedulaxActionPerformed

    private void txt_cedulaxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cedulaxFocusGained
        // TODO add your handling code here:
        if (txt_cedulax.getText().length() == 10 || txt_cedulax.getText().length() == 13) {
            VaciarTexto.limpiar_texto(jPanel2);
            VaciarTexto.limpiar_texto(jPanel6);
            VaciarTexto.limpiar_texto(jPanel7);
            txt_observaciones.setText("");
            buscarOCrearNuevoCLiente(txt_cedulax.getText());
        }

    }//GEN-LAST:event_txt_cedulaxFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JComboBox<String> jcb_FormaPagoPredeterminada;
    public static javax.swing.JComboBox<String> jcb_tipoCLiente;
    public static javax.swing.JTextField txtFechaNaciomiento;
    public static javax.swing.JTextField txt_cedulax;
    public static javax.swing.JTextField txt_celular;
    public static javax.swing.JTextField txt_ciudad;
    public static javax.swing.JLabel txt_codigo;
    public static javax.swing.JTextField txt_dir;
    public static javax.swing.JTextField txt_estadoCivil;
    public static javax.swing.JTextField txt_genero;
    public static javax.swing.JTextField txt_huella;
    public static javax.swing.JTextField txt_mail;
    public static javax.swing.JTextField txt_nacionalidad;
    public static javax.swing.JTextField txt_nombreComercia;
    public static javax.swing.JTextField txt_nombres;
    public static javax.swing.JTextArea txt_observaciones;
    public static javax.swing.JTextField txt_provincia;
    public static javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
