/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Usuarios;

import ClasesAuxiliares.http.ConsultaCedulas;
import Controlador.Coneccion;
import Controlador.Usuarios.ClientesDao;
import Modelo.Clientes;
import Modelo.Tipo_Usuario;
import Modelo.Usuarios;
import Vista.Dialogs.PagoConCheque;
import Vista.Principal;
import Vista.Sat.Crear_Orden;
import Vlidaciones.ProgressBar;
import Vlidaciones.VaciarTexto;
import Vlidaciones.ValidaCedula;
import Vlidaciones.ValidaEmail;
import Vlidaciones.ValidaNUmeros;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.math.BigInteger;
import java.sql.Connection;
import java.sql.Date;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import org.json.JSONObject;

/**
 *
 * @author USUARIO
 */
public class Crear_Clientes extends javax.swing.JInternalFrame {

    public static boolean isLlamadoDesdeNuevoAparato = false;
    public static boolean isllamadoDesdePagoConChque = false;
    
    public static Integer indexPositiotoolBar;
    ValidaEmail obj_valida_email = new ValidaEmail();
    ProgressBar a = new ProgressBar(1000, "Mensaje Inicial");

    /**
     * Creates new form FCUsuarios
     */
    public Crear_Clientes() {
        initComponents();

//        JRootPane rootPane = SwingUtilities.getRootPane(this.jButton1);
//        rootPane.setDefaultButton(this.jButton1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_codigo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txt_ciudad = new javax.swing.JTextField();
        txt_provincia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_genero = new javax.swing.JTextField();
        txt_estadoCivil = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_huella = new javax.swing.JTextField();
        txt_nacionalidad = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_dir = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_mail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        txt_celular = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_nombres = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        txtFechaNaciomiento = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_nombreComercia = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_observaciones = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jcb_tipo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jcb_tipoCLiente = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Nuevo Cliente");
        setToolTipText("");
        setVisible(false);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txt_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, 130, 30));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de eUsuario"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Adicionales"));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(txt_ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 54, 288, -1));
        jPanel6.add(txt_provincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 25, 288, -1));

        jLabel1.setText("Provincia");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 28, -1, -1));

        jLabel2.setText("Ciudad");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 57, -1, -1));

        jLabel14.setText("Genero");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 92, -1, -1));
        jPanel6.add(txt_genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 89, 41, -1));
        jPanel6.add(txt_estadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 122, 67, -1));

        jLabel11.setText("Estado Civil");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 125, -1, -1));

        jLabel16.setText("Huella");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 92, -1, -1));
        jPanel6.add(txt_huella, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 89, 162, -1));

        txt_nacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nacionalidadActionPerformed(evt);
            }
        });
        jPanel6.add(txt_nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 122, 94, -1));

        jLabel15.setText("Nacionalidad");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 125, -1, -1));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 272, 371, 160));
        jPanel2.add(txt_dir, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 243, 354, -1));

        jLabel6.setText("Direccion");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 220, -1, -1));

        txt_mail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_mailKeyPressed(evt);
            }
        });
        jPanel2.add(txt_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 197, 354, -1));

        jLabel9.setText("Email");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 174, -1, -1));
        jPanel2.add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 145, 110, -1));
        jPanel2.add(txt_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 145, 149, -1));

        jLabel8.setText("Celular");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 122, 67, -1));

        jLabel7.setText("Convencional");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 122, 88, -1));
        jPanel2.add(txt_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 93, 354, -1));

        jLabel5.setText("Nombres(*)");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 70, -1, -1));

        txt_cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cedulaActionPerformed(evt);
            }
        });
        txt_cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cedulaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cedulaKeyTyped(evt);
            }
        });
        jPanel2.add(txt_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 41, 119, -1));

        txtFechaNaciomiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaNaciomientoActionPerformed(evt);
            }
        });
        jPanel2.add(txtFechaNaciomiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 145, 84, -1));

        jLabel13.setText("Fech. Nac.");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        jLabel4.setText("Cedula(*)");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 18, 110, -1));

        jLabel17.setText("Nombre Comercial");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));
        jPanel2.add(txt_nombreComercia, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 220, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 390, 440));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Observaciones"));

        txt_observaciones.setColumns(20);
        txt_observaciones.setRows(5);
        jScrollPane1.setViewportView(txt_observaciones);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 370, -1));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Foto"));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 350, 300));

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setBackground(new java.awt.Color(102, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jButton1PropertyChange(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jcb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE" }));
        jcb_tipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcb_tipoItemStateChanged(evt);
            }
        });
        jcb_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_tipoActionPerformed(evt);
            }
        });

        jLabel10.setText("Forma de Pago");

        jcb_tipoCLiente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INACTIVO" }));

        jLabel3.setText("Tipo Cliente");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jcb_tipoCLiente, 0, 197, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel3))
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_tipoCLiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 760, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cedulaKeyTyped

    }//GEN-LAST:event_txt_cedulaKeyTyped

    private void txt_mailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_mailKeyPressed
        // TODO add your handling code here:
        if (obj_valida_email.validaEmail(txt_mail.getText())) {
            txt_mail.setBackground(Color.white);
        } else {
            txt_mail.setBackground(Color.cyan);
    }//GEN-LAST:event_txt_mailKeyPressed
        //if(txt_cedula.get>= 10 ||txt_cedula.getSize()==13)

    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ClientesDao obj = new ClientesDao();
        Clientes u = new Clientes();
        // Object objcb_tipo = jcb_tipo.getSelectedItem();
        // Object objcb_estado = jcb_estado.getSelectedItem();

        if (!txt_cedula.getText().isEmpty() && !txt_nombres.getText().isEmpty()) {

            u.setCedula(txt_cedula.getText());
            u.setNombre(txt_nombres.getText());
            u.setTelefono(txt_telefono.getText());
            u.setCelular(txt_celular.getText());
            u.setMail(txt_mail.getText());
            u.setDireccion(txt_dir.getText());
            u.setProvincia(txt_provincia.getText());
            u.setCiudad(txt_ciudad.getText());
            u.setNacionalidad(txt_nacionalidad.getText());
            u.setPagoPredeterminado(1);
            u.setEstadoCivil(txt_estadoCivil.getText());
            u.setGenereo(txt_genero.getText());
            u.setHuella(txt_huella.getText());
//            long d = tarea.getFecha().getTime();
//            java.sql.Date fecha = new java.sql.Date(d);
            u.setNacimiento(txtFechaNaciomiento.getText());

            if (evt.getActionCommand().equals("Actualizar")) {

                System.out.println("Vista.Usuarios.CrearUsuarios.jButton1ActionPerformed()DDDDXXXXXCODIGO: " + txt_codigo.getText());
                u.setCodigo(Integer.parseInt(txt_codigo.getText()));
                obj.modificar(u);
                if (isLlamadoDesdeNuevoAparato) {
                    Crear_Orden.txtRUC.setText(u.getCedula());
                    Crear_Orden.txtNombres.setText(u.getNombre());
                    Crear_Orden.newCliente = u;
                    this.dispose();
                }
                this.dispose();
                ClientesDao cu = new ClientesDao();
                String sql = "select * from Clientes  order BY Nombres ";

                Buscar_Clientes.jTable1.setModel(cu.Buscar_table_only_Activos(sql));

            } else {

                obj.guardar(u);
                if(isllamadoDesdePagoConChque){
                    PagoConCheque.cliente=u;
                    PagoConCheque.txtCliente.setText(u.getNombre());
                    
                    
                    this.dispose();
                }
                if (isLlamadoDesdeNuevoAparato) {
                    Crear_Orden.newCliente = u;
                    Crear_Orden.txtRUC.setText(u.getCedula());
                    Crear_Orden.txtNombres.setText(u.getNombre());
                    this.dispose();
                }
            }

            VaciarTexto limpiar = new VaciarTexto();
            limpiar.limpiar_texto(jPanel2);

            System.out.println("Vista.Usuarios.FUsuarios.jButton1ActionPerformed()");
dispose();
        } else {
//ProgressBar a = new ProgressBar(1000, "LLenar los campos Obligatorios");
            a.setProgressBar_mensajae("Debes LLenar los campos Obligatorios");
//        
//            JOptionPane.showMessageDialog(null, "Debes LLenar los campos Obligatorios",
//                    "Información", JOptionPane.CLOSED_OPTION);

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed

    }//GEN-LAST:event_formInternalFrameClosed

    private void jcb_tipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcb_tipoItemStateChanged
        // TODO add your handling code here:
//         if (evt.getStateChange() == 1) {
//            for (Tipo_Usuario p : lista_tipos_usuarios) {
//                if (p.getTipo().equals(jcb_tipo.getSelectedItem())) {
//                    codigoTipoUsuario = p.getCodigo();
//                }
//            }
//        }

    }//GEN-LAST:event_jcb_tipoItemStateChanged

    private void jButton1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jButton1PropertyChange
        // TODO add your handling code here:
        //if(evt.getPropertyName())
        if (jButton1.getText().equals("Actualizar")) {
            //jcb_estado.setSelectedItem("");
        }
        System.out.println("Vista.Usuarios.Crear_Usuarios.jButton1Prop,,,,,,,,ertyChange()" + evt.getNewValue());
    }//GEN-LAST:event_jButton1PropertyChange
//
    private void jcb_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_tipoActionPerformed

    private void txtFechaNaciomientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaNaciomientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaNaciomientoActionPerformed

    private void txt_cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cedulaActionPerformed

    private void txt_nacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nacionalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nacionalidadActionPerformed

    public static boolean buscarOCrearNuevoCLiente(String ruc) {
        boolean existeCliente = false;
        Clientes c = new Clientes();
        ClientesDao cDao = new ClientesDao();

        c = cDao.buscarConCedulaLike(ruc);
        System.out.println(" aaasdddd  :  "+c.getCedula());
        if (c.getCedula() == null) {
            if (ruc.length() == 10) {
                boolean ok = false;

                ok = ValidaCedula.validaRUC(ruc);
                if (ok) {
                    JSONObject myResponse;
                    try {
                        myResponse = ConsultaCedulas.getInfoRegistroCivil(ruc);
                        txtFechaNaciomiento.setText(myResponse.getString("dob"));
                        txt_nacionalidad.setText(myResponse.getString("nationality"));
                        txt_dir.setText(myResponse.getString("streets"));
                        txt_nombres.setText(myResponse.getString("name"));
                        txt_genero.setText(myResponse.getString("genre"));
                        txt_huella.setText(myResponse.getString("fingerprint"));
                        txt_estadoCivil.setText(myResponse.getString("civilstate"));
                        txt_provincia.setText(myResponse.getString("residence"));
                        txt_cedula.setText(myResponse.getString("identity"));
                        ok = false;
                    } catch (Exception ex) {
                        Logger.getLogger(Crear_Clientes.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }

            if (ruc.length() == 13) {
                boolean ok = false;
                //ValidaCedula v = new ValidaCedula();
                //ok = v.isCedula(txt_cedula.getText());
                ok = ValidaCedula.validaRUC(ruc);
                if (ok) {
                    JSONObject myResponse;
                    try {

                        myResponse = ConsultaCedulas.getinfoSRI(ruc);
                        JSONObject mydir = ConsultaCedulas.getinfoSRIDireccion(ruc);
                        System.out.println("" + mydir);
                        System.out.println("RUC: " + myResponse.getString("numeroRuc"));
                        txt_cedula.setText(myResponse.getString("numeroRuc"));
                        txt_nacionalidad.setText("ECUATORIANA");
                        txt_dir.setText("");
                        txt_nombres.setText(myResponse.getString("razonSocial"));
                        /// txtFechaNaciomiento.setText(myResponse.getString("fechaInicioActividades"));
                        txt_genero.setText("N/A");
                        txt_huella.setText("N/A");

                        if (!myResponse.isNull("nombreComercial")) {

                            txt_nombreComercia.setText(myResponse.getString("razonSocial"));
                        }
                        //else {
//                            txt_nombreComercia.setText(myResponse.getString("nombreComercial"));
//                        }
                        if (!myResponse.isNull("estadoPersonaNatural")) {
                            txt_estadoCivil.setText(myResponse.getString("estadoPersonaNatural"));
                        }
                        txt_observaciones.setText("OBLIGADO: " + myResponse.getString("obligado") + "\n" + myResponse.getString("actividadContribuyente") + "\n");
                        if (!myResponse.isNull("nombreFantasiaComercial")) {
                            System.out.println("Nombre Comercial: " + myResponse.getString("nombreFantasiaComercial"));
                        }

                        if (!mydir.isNull("direccionCompleta")) {
                            System.out.println("direccionCompleta: " + mydir.getString("direccionCompleta"));
                            String direccion = mydir.getString("direccionCompleta");
                            txt_dir.setText(direccion);
                            String separador = Pattern.quote("/");
                            String[] arrayDireccion = direccion.split(separador);

// En este momento tenemos un array en el que cada elemento es un color.
                            for (int i = 0; i < arrayDireccion.length; i++) {
                                System.out.println(arrayDireccion[i]);
                                txt_provincia.setText(arrayDireccion[1]);
                                txt_ciudad.setText(arrayDireccion[2]);
                                if (arrayDireccion.length == 3) {
                                    txt_dir.setText(arrayDireccion[3]);
                                }
                                if (arrayDireccion.length == 2) {
                                    txt_dir.setText(arrayDireccion[2]);
                                }

                            }
                        }
//                        if (!myResponse.isNull("agenteRepresentante")) {
//                            System.out.println("Representante Nombre: " + myResponse.getString("agenteRepresentante"));
//                        }
//                        if (!myResponse.isNull("representanteLegal")) {
//                            System.out.println("Representante CI: " + myResponse.getString("representanteLegal"));
//                        }
//                        System.out.println("Sociedad: " + myResponse.getString("personaSociedad"));

                        ok = false;
                    } catch (Exception ex) {
                        Logger.getLogger(Crear_Clientes.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }

        } else {
            if (isLlamadoDesdeNuevoAparato) {
                existeCliente = true;
                Crear_Orden.newCliente = c;
//                
//                txt_celular.setText(c.getCelular());
//                txt_ciudad.setText(c.getCiudad());
//                txt_codigo.setText(c.getCodigo().toString());
//                txt_dir.setText(c.getDireccion());
//                txt_estadoCivil.setText(c.getEstadoCivil());
//                txt_genero.setText(c.getGenereo());
//                txt_huella.setText(c.getHuella());
//                txt_mail.setText(c.getMail());
//                txt_nacionalidad.setText(c.getNacionalidad());
//                txt_nombreComercia.setText(c.getNombre());
//                txt_nombres.setText(c. getNombre());
//                txt_observaciones.setText(c.getObservaciones());
//                txt_provincia.setText(c.getProvincia());
//                txt_telefono.setText(c.getTelefono());
            }else{
JOptionPane.showMessageDialog(null, "El Cliente ya esta resgistrado..");
            }

        }
        return existeCliente;
    }

    public static boolean buscarOCrearNuevoCLientevERIFICA(String ruc) {
        boolean existeCliente = false;
        Clientes c = new Clientes();
        ClientesDao cDao = new ClientesDao();

        c = cDao.buscarConCedulaLike(ruc);
        if (c.getCedula() == null) {
            if (ruc.length() == 10) {
                boolean ok = false;

                ok = ValidaCedula.validaRUC(ruc);
                if (ok) {
                    JSONObject myResponse;
                    try {
                        ok = false;
                    } catch (Exception ex) {
                        Logger.getLogger(Crear_Clientes.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }

            if (ruc.length() == 13) {
                boolean ok = false;
                ok = ValidaCedula.validaRUC(ruc);
                if (ok) {
                    JSONObject myResponse;
                    try {
                    } catch (Exception ex) {
                        Logger.getLogger(Crear_Clientes.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }

        } else {
            if (isLlamadoDesdeNuevoAparato) {
                existeCliente = true;
                Crear_Orden.newCliente = c;

              //  txt_nacionalidad.setText(c.getNacionalidad());
            }

        }
        return existeCliente;
    }
    private void txt_cedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cedulaKeyPressed
        // TODO add your handling code here:
        if ((evt.getKeyCode() == KeyEvent.VK_ENTER && txt_cedula.getText().length() == 10) || (evt.getKeyCode() == KeyEvent.VK_ENTER && txt_cedula.getText().length() == 13)) {
            buscarOCrearNuevoCLiente(txt_cedula.getText());
        }
//            if () {
//
//            }else {
//                JOptionPane.showMessageDialog(null, "La Persona o Empresa, Ya se encuentra registrada..", " AVISO ", JOptionPane.INFORMATION_MESSAGE);
//            }
//        } else {
//            txt_celular.setText("");
//            txt_ciudad.setText("");
//            txt_codigo.setText("");
//            txt_dir.setText("");
//            txt_estadoCivil.setText("");
//            txt_genero.setText("");
//            txt_huella.setText("");
//            txt_mail.setText("");
//            txt_nacionalidad.setText("");
//            txt_nombreComercia.setText("");
//            txt_nombres.setText("");
//            txt_observaciones.setText("");
//            txt_provincia.setText("");
//            txt_telefono.setText("");
//
//        }
//

    }//GEN-LAST:event_txt_cedulaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JComboBox<String> jcb_tipo;
    public static javax.swing.JComboBox<String> jcb_tipoCLiente;
    public static javax.swing.JTextField txtFechaNaciomiento;
    public static javax.swing.JTextField txt_cedula;
    public static javax.swing.JTextField txt_celular;
    public static javax.swing.JTextField txt_ciudad;
    public static javax.swing.JLabel txt_codigo;
    public static javax.swing.JTextField txt_dir;
    public static javax.swing.JTextField txt_estadoCivil;
    public static javax.swing.JTextField txt_genero;
    public static javax.swing.JTextField txt_huella;
    public static javax.swing.JTextField txt_mail;
    public static javax.swing.JTextField txt_nacionalidad;
    public static javax.swing.JTextField txt_nombreComercia;
    public static javax.swing.JTextField txt_nombres;
    public static javax.swing.JTextArea txt_observaciones;
    public static javax.swing.JTextField txt_provincia;
    public static javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
