/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Usuarios;

import ClasesAuxiliares.AutocompleteJComboBox;
import ClasesAuxiliares.StringSearchable;
import ClasesAuxiliares.http.ConsultaCedulas;
import Controlador.Coneccion;
import Controlador.Usuarios.ClientesDao;
import Controlador.Usuarios.SmenuDao_prueba;
import Controlador.Usuarios.Tipo_UsuariosDao;
import Controlador.Usuarios.UsuariosDao;
import Modelo.Clientes;
import ClasesAuxiliares.debug.Deb;
import Modelo.Tipo_Usuario;
import Modelo.Usuarios;
import Modelo.smenu;
import Vista.Principal;
import static Vista.Usuarios.Crear_Clientes.buscarOCrearNuevoCLiente;
import Vlidaciones.ProgressBar;
import Vlidaciones.VaciarTexto;
import Vlidaciones.ValidaCedula;
import Vlidaciones.ValidaEmail;
import Vlidaciones.ValidaNUmeros;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.math.BigInteger;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import org.json.JSONObject;
import static Vista.Usuarios.Crear_Clientes.jcb_FormaPagoPredeterminada;

/**
 *
 * @author USUARIO
 */
public class Crear_Usuarios extends javax.swing.JInternalFrame {

    ValidaEmail obj_valida_email = new ValidaEmail();
    ProgressBar a = new ProgressBar(3000, "Mensaje Inicial");
    ArrayList<Tipo_Usuario> lista_tipos_usuarios = new ArrayList<Tipo_Usuario>();
    Integer codigoTipoUsuario = -1;
    Object items_jcb_estado;
    public static Object setItemSelect;
    public static String actualizarSiNO;
    public static Integer indexPositiotoolBar;

    /**
     * Creates new form FCUsuarios
     */
    public Crear_Usuarios() {
        initComponents();
///////// jcb editable
        jcb_tipo.setEditable(true);

        JTextField tf = (JTextField) jcb_tipo.getEditor().getEditorComponent();
        tf.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Deb.consola(".keyTyped()qqqq key jcb");
                jcb_tipo.showPopup();
            }
        });

///
        List<String> listJcb = new ArrayList<String>();
        Tipo_UsuariosDao objDao = new Tipo_UsuariosDao();
        lista_tipos_usuarios = objDao.listar();
///lleno lista tipo d eusuarios
        for (Tipo_Usuario p : lista_tipos_usuarios) {

            jcb_tipo.addItem(p.getTipo());

            listJcb.add(p.getTipo());

        }
        try {

            if (actualizarSiNO.equals("si")) {
                jcb_tipo.setSelectedItem(setItemSelect);

            }
        } catch (Exception e) {
        }

//        StringSearchable searchable = new StringSearchable(listJcb);
//        AutocompleteJComboBox combo = new AutocompleteJComboBox(searchable);
//        jPanel1.add(combo);
//        combo.setLightWeightPopupEnabled(true);
//        combo.setVisible(true);
//        
        /// selecciono registro actial en editar 
////        int num = jcb_tipo.getItemCount();
////        for (int i = 0; i < num; i++) {
////            // Deb.consola("Vista.Usuarios.Crear_Usuarios.<init>()"+jcb_tipo.getItemAt(i));
////            Object items_jcb_estado = jcb_tipo.getItemAt(i);
////
////            //Deb.consola("Vista.Usuarios.Crear_Usuarios.<init>()" + items_jcb_estado);
////        }
        JRootPane rootPane = SwingUtilities.getRootPane(this.jButton1);
        rootPane.setDefaultButton(this.jButton1);

        SmenuDao_prueba s = new SmenuDao_prueba();
        smenu ss= new smenu();
        ss.setCodigo(1);
        ss.setCodigo_menu(33);
        ss.setMenu("sdsdsdf");
        ss.setUrl("fsdfsdfsdfsdfsfdsdfsfd");
        ss.setVisible("sssssiiii");
        Object o;
        o= (Object) ss;
        s.insertInto(ss);
        JOptionPane.showMessageDialog(null, "dsaaaaaaaaaaaaaaaaaaaaaaaa");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_nombres = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_mail = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_celular = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_dir = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcb_estado = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jcb_tipo = new javax.swing.JComboBox<>();
        txt_pass = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txt_codigo = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Nuevo Usuario");
        setToolTipText("");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de eUsuario"));

        jLabel4.setText("Cedula(*)");

        txt_cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cedulaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cedulaKeyTyped(evt);
            }
        });

        jLabel5.setText("Nombres(*)");

        jLabel6.setText("Direccion");

        txt_mail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_mailKeyPressed(evt);
            }
        });

        jLabel7.setText("Telefono");

        jLabel8.setText("Celular");

        jLabel9.setText("Email");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de eUsuario"));

        jLabel1.setText("Nombre de Usuario(*)");

        jLabel2.setText("Contraseña(*)");

        jLabel3.setText("Estado:");

        jcb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INACTIVO" }));

        jLabel10.setText("Tipo(*)");

        jcb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE" }));
        jcb_tipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcb_tipoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_user)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(104, 104, 104))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jcb_tipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(103, 103, 103))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jcb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_dir))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nombres))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_celular, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_mail))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txt_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txt_celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txt_dir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 375));

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 160, 66));

        jButton1.setBackground(new java.awt.Color(102, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jButton1PropertyChange(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 150, 66));
        getContentPane().add(txt_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 130, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cedulaKeyTyped
        // TODO add your handling code here:
        ValidaNUmeros val = new ValidaNUmeros();
        val.keyTyped(evt);
        //ValidaCedula vc = new ValidaCedula();
        try {
            //    vc.isCedula(txt_cedula.getText());
        } catch (Exception ex) {
            Logger.getLogger(Crear_Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_txt_cedulaKeyTyped

    private void txt_mailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_mailKeyPressed
        // TODO add your handling code here:
        if (obj_valida_email.validaEmail(txt_mail.getText())) {
            txt_mail.setBackground(Color.white);
        } else {
            txt_mail.setBackground(Color.cyan);
    }//GEN-LAST:event_txt_mailKeyPressed
        //if(txt_cedula.get>= 10 ||txt_cedula.getSize()==13)

    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String passText = new String(txt_pass.getPassword());
        UsuariosDao obj = new UsuariosDao();
        Usuarios u = new Usuarios();
        // Object objcb_tipo = jcb_tipo.getSelectedItem();
        // Object objcb_estado = jcb_estado.getSelectedItem();

        if (!txt_cedula.getText().isEmpty() && !txt_nombres.getText().isEmpty() && !txt_user.getText().isEmpty() && !passText.isEmpty()) {
            if (codigoTipoUsuario != -1) {
                u.setCedula(txt_cedula.getText());
                u.setNombre(txt_nombres.getText());
                u.setTelefono(txt_telefono.getText());
                u.setCelular(txt_celular.getText());
                u.setMail(txt_mail.getText());
                u.setDireccion(txt_dir.getText());
                u.setUsuario(txt_user.getText());
                u.setPassword(passText);
                u.setEstado(jcb_estado.getSelectedItem().toString());
                u.setEstado(jcb_estado.getSelectedItem().toString());

                // jcb_estado.getModel().setSelectedItem(new ComboItem(3, "banana"));
                u.setTipo_Usuario_codigo(codigoTipoUsuario);

                if (evt.getActionCommand().equals("Actualizar")) {

                    Deb.consola("Vista.Usuarios.CrearUsuarios.jButton1ActionPerformed()");
                    u.setCodigo(Integer.parseInt(txt_codigo.getText()));
                    obj.modificar(u);
                    this.dispose();
                    UsuariosDao cu = new UsuariosDao();
                    String sql = "select usuarios.*,tipos_usuarios.tipo from usuarios inner join tipos_usuarios on tipos_usuarios.codigo=usuarios.Tipo_Usuario_codigo order BY usuarios.Nombres LIMIT 0, 50";

                    Buscar_usuarios.jTable1.setModel(cu.Buscar_table_only_Activos(sql));

                } else {

                    obj.guardar(u);
                }

                VaciarTexto limpiar = new VaciarTexto();
                limpiar.limpiar_texto(jPanel1);
                limpiar.limpiar_texto(jPanel2);

                Deb.consola("Vista.Usuarios.FUsuarios.jButton1ActionPerformed()");
            } else {
                a.setProgressBar_mensajae("Selccionar un Tipo de Usuario Valido..");
            }
        } else {
//ProgressBar a = new ProgressBar(1000, "LLenar los campos Obligatorios");
            a.setProgressBar_mensajae("Debes LLenar los campos Obligatorios");
//        
//            JOptionPane.showMessageDialog(null, "Debes LLenar los campos Obligatorios",
//                    "Información", JOptionPane.CLOSED_OPTION);

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:


    }//GEN-LAST:event_formInternalFrameClosed

    private void jcb_tipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcb_tipoItemStateChanged
        // TODO add your handling code here:
        //if(jcb_tipo.getSelectedItem
        if (evt.getStateChange() == 1) {
            for (Tipo_Usuario p : lista_tipos_usuarios) {
                if (p.getTipo().equals(jcb_tipo.getSelectedItem())) {
                    codigoTipoUsuario = p.getCodigo();
                }
            }
            // Deb.consola("Vista.Usuarios.Crear_Usuarios.jcb_tipoItemStateChanged()slectedddddddddddddddddddddddd");

        }

        //Deb.consola("Vista.Usuarios.Crear_Usuarios.jcb_tipoItemStateChanged()"+jcb_tipo.getSelectedItem());
        //Deb.consola("Vista.Usuarios.Crear_Usuarios.jcb_tipoItemStateChanged()" +evt.toString());
    }//GEN-LAST:event_jcb_tipoItemStateChanged

    private void jButton1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jButton1PropertyChange
        // TODO add your handling code here:
        //if(evt.getPropertyName())
        if (jButton1.getText().equals("Actualizar")) {
            jcb_estado.setSelectedItem("");
        }
        Deb.consola("Vista.Usuarios.Crear_Usuarios.jButton1Prop,,,,,,,,ertyChange()" + evt.getNewValue());
    }//GEN-LAST:event_jButton1PropertyChange

    public static boolean buscarOCrearNuevoUsuario(String ruc) {
        boolean existeCliente = false;
        Usuarios c = new Usuarios();
        UsuariosDao cDao = new UsuariosDao();

        c = cDao.buscarConCedula(ruc);
        Deb.consola(" aaasdddd  :  " + c.getCedula());
        if (c.getCedula() == null) {
            if (ruc.length() == 10) {
                boolean ok = false;

                ok = ValidaCedula.validaRUC(ruc);
                if (ok) {
                    JSONObject myResponse;
                    try {
                        myResponse = ConsultaCedulas.getInfoRegistroCivil(ruc);
//                        txtFechaNaciomiento.setText(myResponse.getString("dob"));
//                        txt_nacionalidad.setText(myResponse.getString("nationality"));
                        txt_dir.setText(myResponse.getString("streets"));
                        txt_nombres.setText(myResponse.getString("name"));
//                        txt_genero.setText(myResponse.getString("genre"));
//                        txt_huella.setText(myResponse.getString("fingerprint"));
//                        txt_estadoCivil.setText(myResponse.getString("civilstate"));
//                        txt_provincia.setText(myResponse.getString("residence"));
                        txt_cedula.setText(myResponse.getString("identity"));
                        ok = false;
                    } catch (Exception ex) {
                        Logger.getLogger(Crear_Clientes.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }else{
            JOptionPane.showMessageDialog(null, "Error de Cedula..");
            }
        } else {
            JOptionPane.showMessageDialog(null, "El Cliente ya esta resgistrado..");
        }    
    return existeCliente ;
}
    private void txt_cedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cedulaKeyReleased
        // TODO add your handling code here:

        if ((evt.getKeyCode() == KeyEvent.VK_ENTER && txt_cedula.getText().length() == 10) || (evt.getKeyCode() == KeyEvent.VK_ENTER && txt_cedula.getText().length() == 13)) {
            buscarOCrearNuevoUsuario(txt_cedula.getText());
        }
    }//GEN-LAST:event_txt_cedulaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JComboBox<String> jcb_estado;
    public static javax.swing.JComboBox<String> jcb_tipo;
    public static javax.swing.JTextField txt_cedula;
    public static javax.swing.JTextField txt_celular;
    public static javax.swing.JLabel txt_codigo;
    public static javax.swing.JTextField txt_dir;
    public static javax.swing.JTextField txt_mail;
    public static javax.swing.JTextField txt_nombres;
    public static javax.swing.JPasswordField txt_pass;
    public static javax.swing.JTextField txt_telefono;
    public static javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
