/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Usuarios;

import ClasesAuxiliares.MaquinaDao;
import ClasesAuxiliares.NewConfigfile;
import Controlador.Coneccion;
import Controlador.Ejemplo;
import Controlador.ProbarConexion;
import Controlador.Usuarios.BodegasDao;
import Controlador.Usuarios.CajasDao;
import Controlador.Usuarios.Config2Dao;
import Controlador.Usuarios.Config_EquiposDao;
import Controlador.Usuarios.DatosEmpresaDao;
import Controlador.Usuarios.EquiposDao;
import Modelo.Bodegas;
import Modelo.Cajas;
import Modelo.Config2;
import Modelo.ConfigSofia;
import Modelo.Config_Equipos;
import Modelo.DatosEmpresa;
import Modelo.Equipos;
import static Vista.Usuarios.Configuracion.listImpresoras;
import Vista.alertas.MnesajesOption;
import Vista.alertas.alerta;
import impresoras.ServicioDeImpresion;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Frame;
import java.io.IOException;
import static java.lang.System.exit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.border.Border;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author USUARIO
 */
public class NuevoEquipo extends javax.swing.JDialog {

    /**
     * Creates new form ConfigurarServidor
     */
/////////////////A
/////////////////////////////////////////////////////////
    ArrayList<Cajas> lista = new ArrayList<Cajas>();
    public static String cajaNombre = null;
    public static Integer cajaCodigo = null;
    private Integer codigoConfig2 = -1;
    Equipos obj = new Equipos();
    EquiposDao objDao = new EquiposDao();
    MaquinaDao maquina = new MaquinaDao();
    ArrayList<Bodegas> listBodegas = new ArrayList<Bodegas>();
    ArrayList<Config2> listConfig2 = new ArrayList<Config2>();
    boolean isClickedinJCBCompra = false;
    boolean isClickedinJCBVenta = false;
    Config_Equipos cofigracionEquipoNuevo = new Config_Equipos();
    Config_Equipos objConfigEquiposcompra = new Config_Equipos();
    Config_Equipos objConfigEquiposventa = new Config_Equipos();
    Integer codigoNewEquipo = null;
    DefaultListModel model2 = new DefaultListModel();

    public NuevoEquipo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();

        Config2 cf = new Config2();
        Config2Dao cfdao = new Config2Dao();
        DefaultListModel model = new DefaultListModel();
        Integer i = 0;

        listConfig2 = cfdao.listar();
        for (Config2 c : listConfig2) {

            model.add(i, c.getNombre());
            i++;

        }
        jList1.setModel(model);

        CajasDao cajaDao = new CajasDao();
        Cajas caja = new Cajas();
        lista = cajaDao.listar();
        for (Cajas cajas : lista) {
            jComboBox1.addItem(cajas.getCaja());
            System.out.println("Cajassss: " + cajas.getCaja());
        }

        BodegasDao bDao = new BodegasDao();
        listBodegas = bDao.listar();
        for (Bodegas b : listBodegas) {
            jcb_BodegaPredeterminadCOmpra.addItem(b.getBodegaID() + "-" + b.getBodega());
            jcb_BodegaPredeterminadventas.addItem(b.getBodegaID() + "-" + b.getBodega());
        }
        jlnombrereal.setText(maquina.getNombreEquipo());
        txt_nombreSoft.setText(maquina.getNombreEquipo() + Math.random());
        llenarJTree();

        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_nombreSoft = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jlnombrereal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSec1 = new javax.swing.JTextField();
        txtSec2 = new javax.swing.JTextField();
        txtSec3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_bodegaPredeterminadaEnCompras = new javax.swing.JLabel();
        txt_bodegaPredeterminadaEnVENTAS = new javax.swing.JLabel();
        jcb_BodegaPredeterminadCOmpra = new javax.swing.JComboBox<>();
        jcb_BodegaPredeterminadventas = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("NOMBRE REAL");

        jLabel2.setText("SECUENCIA");

        txtSec1.setText("001");

        txtSec2.setText("001");

        txtSec3.setText("000000001");

        jLabel3.setText("CAJA PREDETERMINADA");

        txt_bodegaPredeterminadaEnCompras.setText("BODEGA PREDETERMINADA EN COMPRAS");

        txt_bodegaPredeterminadaEnVENTAS.setText("BODEGA PREDETERMINADA EN VENTAS");

        jcb_BodegaPredeterminadCOmpra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        jcb_BodegaPredeterminadCOmpra.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcb_BodegaPredeterminadCOmpraItemStateChanged(evt);
            }
        });
        jcb_BodegaPredeterminadCOmpra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jcb_BodegaPredeterminadCOmpraMouseReleased(evt);
            }
        });
        jcb_BodegaPredeterminadCOmpra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_BodegaPredeterminadCOmpraActionPerformed(evt);
            }
        });

        jcb_BodegaPredeterminadventas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        jcb_BodegaPredeterminadventas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcb_BodegaPredeterminadventasItemStateChanged(evt);
            }
        });
        jcb_BodegaPredeterminadventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jcb_BodegaPredeterminadventasMouseReleased(evt);
            }
        });
        jcb_BodegaPredeterminadventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_BodegaPredeterminadventasActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        jComboBox1.setName(""); // NOI18N
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel4.setText("ALIAS DEL EQUIPO");

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 175, 31));
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_bodegaPredeterminadaEnVENTAS)
                            .addComponent(txt_bodegaPredeterminadaEnCompras)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcb_BodegaPredeterminadventas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcb_BodegaPredeterminadCOmpra, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSec1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSec2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSec3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_nombreSoft, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlnombrereal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(350, 350, 350))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlnombrereal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombreSoft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSec3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSec2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSec1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_bodegaPredeterminadaEnCompras)
                    .addComponent(jcb_BodegaPredeterminadCOmpra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_BodegaPredeterminadventas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_bodegaPredeterminadaEnVENTAS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("COnfiguracion"));

        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jList2);

        jList1.setEnabled(false);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void llenarJTree() {
        DefaultMutableTreeNode raiz = new DefaultMutableTreeNode(jlnombrereal.getText());
        for (Config2 config2 : listConfig2) {
            DefaultMutableTreeNode nodo = new DefaultMutableTreeNode(config2.getNombre());
            raiz.add(nodo);

            switch (config2.getNombre()) {
                case "IMPRESORA TICKETS":
                    List<String> listaimpresoras;
                    listaimpresoras = ServicioDeImpresion.getListadeImpresoras();
                    for (String listaimpresora : listaimpresoras) {
                        DefaultMutableTreeNode nodox = new DefaultMutableTreeNode(listaimpresora);
                        nodo.add(nodox);
                    }
                    break;
                case "IMPRESORA FACTURAS":
                    List<String> listaimpresoras2;
                    listaimpresoras2 = ServicioDeImpresion.getListadeImpresoras();
                    for (String listaimpresora : listaimpresoras2) {
                        DefaultMutableTreeNode nodox = new DefaultMutableTreeNode(listaimpresora);
                        nodo.add(nodox);
                    }

                    break;
                case "FORMA DE PAGO PREDETERMINADA":

                    break;
                case "BODEGA PREDETERMINADA EN COMPRA":
                    break;
                case "BODEGA PREDETERMINADA EN VENTA":
                    break;
                case "VER IMAAGEN":
                    break;
                case "FACTURA TIRILLAS O CON FORMATO":
                    break;
                case "TICKET TIRILLAS O CON FORMATO":
                    break;

                case "PROFORMA TIRILLAS O CON FORMATO":
                    break;
                case "ACTIVAR CONTROL EFECTIVO":
                    break;
                case "FORMATO FACTURA":
                    break;
                case "FORMATO TICKET":
                    break;
                case "FORMATO PROFORMA ":
                    break;

            }
        }
        DefaultTreeModel model = new DefaultTreeModel(raiz);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (isClickedinJCBCompra && isClickedinJCBVenta) {
            if (cajaCodigo != null && cajaNombre != null) {
                if (txtSec1.getText().length() == 3 && txtSec2.getText().length() == 3 && txtSec3.getText().length() == 9) {

                    obj.setCajas_Codigo(cajaCodigo);
                    obj.setCajas_Nombre(cajaNombre);
                    obj.setIp(maquina.getIpEquipo());
                    obj.setNombreReal(maquina.getNombreEquipo());
                    obj.setNombreSof(maquina.getNombreEquipo() + "_" + txt_nombreSoft.getText());
                    obj.setSecuencia1(txtSec1.getText());
                    obj.setSecuencia2(txtSec2.getText());
                    obj.setSecuencia3(txtSec3.getText());
                    codigoNewEquipo = objDao.guardar(obj);
                    jcb_BodegaPredeterminadCOmpra.setEnabled(false);
                    jcb_BodegaPredeterminadventas.setEnabled(false);
                    jComboBox1.setEnabled(false);
                    jList1.setEnabled(true);
                    /////////////////////////////////
                    //crear todas la configuraciones  por defecto vacias
                    ///////////////crearla configuracioninicialocargarla
                    for (Config2 c : listConfig2) {
                        Config_Equipos configEq = new Config_Equipos();
                        Config_EquiposDao configEqDao = new Config_EquiposDao();
                        configEq.setConfig2_codigo(c.getCodigo());
                        configEq.setEquipos_codigo(codigoNewEquipo);
                        configEq.setNombre(c.getNombre());
                        configEq.setValor1("N/A");
                        boolean resp = configEqDao.guardar(configEq);
                    }
                    //////////////////////////////////
                } else {
                    JOptionPane.showMessageDialog(null, "Secuencal mal formado..");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Debe Seleccionar una Caja..");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe Seleccionar Bodegas Predeterminadas para Compra y  Venta");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jcb_BodegaPredeterminadCOmpraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcb_BodegaPredeterminadCOmpraItemStateChanged
        // TODO add your handling code here:
        if (jcb_BodegaPredeterminadCOmpra.getItemCount() > 1 && isClickedinJCBCompra) {
            objConfigEquiposcompra.setValor1(jcb_BodegaPredeterminadCOmpra.getSelectedItem().toString());

        }
    }//GEN-LAST:event_jcb_BodegaPredeterminadCOmpraItemStateChanged

    private void jcb_BodegaPredeterminadCOmpraMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcb_BodegaPredeterminadCOmpraMouseReleased
        // TODO add your handling code here:
        isClickedinJCBCompra = true;
    }//GEN-LAST:event_jcb_BodegaPredeterminadCOmpraMouseReleased

    private void jcb_BodegaPredeterminadCOmpraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_BodegaPredeterminadCOmpraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_BodegaPredeterminadCOmpraActionPerformed

    private void jcb_BodegaPredeterminadventasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcb_BodegaPredeterminadventasItemStateChanged
        // TODO add your handling code here:
        if (jcb_BodegaPredeterminadventas.getItemCount() > 1 && isClickedinJCBVenta) {
            //objConfigEquipos.setValor2(jcb_BodegaPredeterminadventas.getSelectedItem().toString());
            objConfigEquiposventa.setValor1(jcb_BodegaPredeterminadventas.getSelectedItem().toString());
        }
    }//GEN-LAST:event_jcb_BodegaPredeterminadventasItemStateChanged

    private void jcb_BodegaPredeterminadventasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcb_BodegaPredeterminadventasMouseReleased
        // TODO add your handling code here:
        isClickedinJCBVenta = true;
    }//GEN-LAST:event_jcb_BodegaPredeterminadventasMouseReleased

    private void jcb_BodegaPredeterminadventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_BodegaPredeterminadventasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_BodegaPredeterminadventasActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        System.out.println("Vista.Usuarios.SelectCaja.jComboBox1ItemStateChanged()se ha seleccinadosss");
        if (jComboBox1.getSelectedItem() != null) {
            for (Cajas cajas : lista) {
                if (jComboBox1.getSelectedItem().toString().equals(cajas.getCaja())) {

                    cajaCodigo = cajas.getCodigo();
                    cajaNombre = cajas.getCaja();
                }
                if (jComboBox1.getSelectedItem().toString().equals("Seleccione")) {
                    cajaCodigo = null;
                    cajaNombre = "N/A";
                    JOptionPane.showMessageDialog(null, "Por favor Seleccione una Caja para este Equipo");
                }

            }
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        Integer index = -1;
        jLabel5.setText(jList1.getSelectedValue());

        for (Config2 config2 : listConfig2) {
            if (config2.getNombre().equalsIgnoreCase(jList1.getSelectedValue())) {
                System.out.println("Nombre Coonfig2 sleeccionado: " + jList1.getSelectedValue());
                codigoConfig2 = config2.getCodigo();
                System.out.println("Codigo Coonfig2 sleeccionado: " + codigoConfig2);
            }

        }
        //Integer index = -1;
        Config_Equipos csofi = new Config_Equipos();
        Config_EquiposDao cdao = new Config_EquiposDao();
        csofi = cdao.buscarConfiguracionesdeEquipos(codigoNewEquipo, codigoConfig2);
        model2.clear();
        switch (jList1.getSelectedValue()) {
            case "IMPRESORA TICKETS":

                List<String> listaimpresoras;
                listaimpresoras = ServicioDeImpresion.getListadeImpresoras();
                int i = 0;
                for (String listaimpresora : listaimpresoras) {
                    model2.add(i, listaimpresora);
                    index = i;
                    if (csofi.getValor1().equalsIgnoreCase(listaimpresora)) {                        
                        jList2.setSelectedIndex(index);
                        jLabel5.setText(jLabel5.getText()+" --> "+(csofi.getValor1()));
                    }else{
                        alerta.menajes(csofi.getValor1());
                        jLabel5.setText(csofi.getNombre()+" --> "+(csofi.getValor1()));
                    }
                }
                jList2.setModel(model2);

                break;

            case "IMPRESORA FACTURAS":
                List<String> listaimpresoras2;
                listaimpresoras2 = ServicioDeImpresion.getListadeImpresoras();
                i = 0;
                for (String listaimpresora : listaimpresoras2) {
                    model2.add(i, listaimpresora);
                    //jcb_configoptions.addItem(listaimpresora);

                }
                jList2.setModel(model2);

                //      jcb_configoptions.setPopupVisible(true);
                break;
            case "FORMA DE PAGO PREDETERMINADA":

                break;
            case "BODEGA PREDETERMINADA EN COMPRA":
                break;
            case "BODEGA PREDETERMINADA EN VENTA":
                break;
            case "VER IMAAGEN":
                break;
            case "FACTURA TIRILLAS O CON FORMATO":
                break;
            case "TICKET TIRILLAS O CON FORMATO":
                break;

            case "PROFORMA TIRILLAS O CON FORMATO":
                break;
            case "ACTIVAR CONTROL EFECTIVO":
                break;
            case "FORMATO FACTURA":
                break;
            case "FORMATO TICKET":
                break;
            case "FORMATO PROFORMA ":
                break;

        }
    }//GEN-LAST:event_jList1ValueChanged

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 && codigoConfig2 != -1) {

            //////////////
            //////////////consulto el codigo del config2 seleccionado
            Config_Equipos configEqtoUpdate = new Config_Equipos();
            Config_EquiposDao configEqDaoupdate = new Config_EquiposDao();
            configEqtoUpdate = configEqDaoupdate.buscarConfiguracionesdeEquipos(codigoNewEquipo, codigoConfig2);
            System.out.println("equipo en operacion: " + configEqtoUpdate.toString());
            System.out.println("Codifoxxxx: " + configEqtoUpdate.getCodigo());
            if (configEqtoUpdate.getCodigo() == null) {
                Config_Equipos configEq = new Config_Equipos();
                Config_EquiposDao configEqDao = new Config_EquiposDao();

                configEq.setConfig2_codigo(codigoConfig2);
                configEq.setEquipos_codigo(codigoNewEquipo);
                configEq.setNombre(jList1.getSelectedValue());
                configEq.setValor1(jList2.getSelectedValue());
                boolean resp = configEqDao.guardar(configEq);
                if (resp) {
                    JOptionPane.showMessageDialog(null, "Se regstro: " + jList2.getSelectedValue());
                }
            } else {
                configEqtoUpdate.setValor1(jList2.getSelectedValue());
                Config_EquiposDao configEqDaoupdate2 = new Config_EquiposDao();
                configEqDaoupdate2.ActualizarValor1deConfiguracion(configEqtoUpdate);
            }
            jList2.setSelectionBackground(Color.RED);

        }
        jList2.setSelectionBackground(Color.lightGray);

    }//GEN-LAST:event_jList2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NuevoEquipo dialog = new NuevoEquipo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> jcb_BodegaPredeterminadCOmpra;
    private javax.swing.JComboBox<String> jcb_BodegaPredeterminadventas;
    private javax.swing.JLabel jlnombrereal;
    private javax.swing.JTextField txtSec1;
    private javax.swing.JTextField txtSec2;
    private javax.swing.JTextField txtSec3;
    private javax.swing.JLabel txt_bodegaPredeterminadaEnCompras;
    private javax.swing.JLabel txt_bodegaPredeterminadaEnVENTAS;
    private javax.swing.JTextField txt_nombreSoft;
    // End of variables declaration//GEN-END:variables
}
