/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Usuarios;

import ClasesAuxiliares.KeysEnventos;
import ClasesAuxiliares.Variables;
import Vista.Principal;
import Vista.alertas.alerta;
import Vlidaciones.ValidaNUmeros;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import static login.login.__factory;
import static login.login.__unidadPersistencia;
import persistencia.controllers.FormaspagocJpaController;
import persistencia.controllers.PlanJpaController;
import persistencia.controllers.SriFormasPagoJpaController;
import persistencia.modelos.Formaspagoc;
import persistencia.modelos.Formaspagov;
import persistencia.modelos.Plan;
import persistencia.modelos.SriFormasPago;

/**
 *
 * @author USUARIO
 */
public class NuevaFormaPago extends javax.swing.JInternalFrame {

    /**
     * Creates new form NuevaFormaPago
     */
    boolean _tipoMovimiento_CXC_CXP_selected = false;
    boolean _FormaPagoSelected = false;
    String _tipo_forma_pago = "";
    boolean _afectaaCaja = false;
    Integer _idCuenta_contable = -1;

    private List<SriFormasPago> listaFormasPagoSri = new ArrayList();

    public NuevaFormaPago() {
        initComponents();

        //EntityManagerFactory factory = Persistence.createEntityManagerFactory(__unidadPersistencia, System.getProperties());   
        SriFormasPagoJpaController formpago = new SriFormasPagoJpaController(__factory);
        listaFormasPagoSri = formpago.findSriFormasPagoEntities();
        for (SriFormasPago f : listaFormasPagoSri) {
            jcb_sustentoTributario.addItem(f.getId() + " - " + f.getFormaPago());
        }
        //factory.close();
        this.setSize(585, 448);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_cuentaContable = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jcb_sustentoTributario = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jcb_cxc_cxP = new javax.swing.JComboBox<>();
        jcb_formaPago = new javax.swing.JComboBox<>();
        jrb_afectaCaja = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        cuentaContable = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        txt_cuotas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_entrada = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jcb_cobranza = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txt_diasCredito = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jProgressBar2 = new javax.swing.JProgressBar();

        setClosable(true);
        setTitle("Nueva Forma Pago CXC");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txt_cuentaContable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_cuentaContable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cuentaContableKeyReleased(evt);
            }
        });

        jLabel1.setText("Nombre Forma de Pago");

        jButton1.setBackground(new java.awt.Color(2, 117, 216));
        jButton1.setText("Vincular a Cuenta Contable");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jcb_sustentoTributario.setBackground(new java.awt.Color(255, 204, 51));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo Movimiento"));

        jcb_cxc_cxP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "VENTAS", "COMPRAS" }));
        jcb_cxc_cxP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcb_cxc_cxPItemStateChanged(evt);
            }
        });

        jcb_formaPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "EFECTIVO", "CREDITO", "PLAN ACUMULATIVO" }));
        jcb_formaPago.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcb_formaPagoItemStateChanged(evt);
            }
        });

        jrb_afectaCaja.setText("Afecta a Caja");
        jrb_afectaCaja.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jrb_afectaCajaItemStateChanged(evt);
            }
        });
        jrb_afectaCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_afectaCajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrb_afectaCaja)
                    .addComponent(jcb_cxc_cxP, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_formaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcb_cxc_cxP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcb_formaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jrb_afectaCaja)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextArea1.setColumns(10);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextArea1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        cuentaContable.setBackground(new java.awt.Color(255, 255, 204));

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txt_cuotas.setText("1");
        txt_cuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cuotasActionPerformed(evt);
            }
        });
        txt_cuotas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cuotasKeyReleased(evt);
            }
        });

        jLabel2.setText("# CUOTAS");

        jLabel4.setText("% ENTRADA");

        txt_entrada.setText("0");
        txt_entrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_entradaKeyReleased(evt);
            }
        });

        jLabel5.setText("COBRANZA");

        jcb_cobranza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "DIARIO", "SEMANAL", "QUINCENAL", "MENSUAL" }));
        jcb_cobranza.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcb_cobranzaItemStateChanged(evt);
            }
        });

        jLabel6.setText("DIAS DE CREDITO");

        txt_diasCredito.setText("30");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcb_cobranza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_cuotas))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_diasCredito)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcb_cobranza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_diasCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cuentaContable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(txt_cuentaContable)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jcb_sustentoTributario, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 172, Short.MAX_VALUE))
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(64, 64, 64)))
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(15, 15, 15)
                                .addComponent(txt_cuentaContable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addGap(16, 16, 16)
                                .addComponent(cuentaContable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcb_sustentoTributario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jButton2.setBackground(new java.awt.Color(217, 83, 79));
        jButton2.setText("CANCELAR");

        jButton3.setBackground(new java.awt.Color(92, 184, 92));
        jButton3.setText("GUARDAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jProgressBar2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jProgressBar2.setMaximumSize(new java.awt.Dimension(1001, 14));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jProgressBar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(284, 284, 284))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        Plan cuenta = new Plan();

        try {
            if (_FormaPagoSelected && _tipoMovimiento_CXC_CXP_selected) {
                if (_FormaPagoSelected && _tipoMovimiento_CXC_CXP_selected) {

                    Formaspagoc fpc = new Formaspagoc();

//                if (cuentaContable.getText().isEmpty()) {
//                    fpc.setPlanCodigo(0);
//                } else {
//                    /////////palncuentacontable
//
//                    PlanJpaController planControlller = new PlanJpaController(__factory);
//                    cuenta = planControlller.findCuentaByDescripcion(cuentaContable.getText());
//                }
////
//                ////////formapagosri
                    SriFormasPago sriformapago = new SriFormasPago();
                    SriFormasPagoJpaController sriformpagoController = new SriFormasPagoJpaController(__factory);
                    String formapago = jcb_sustentoTributario.getSelectedItem().toString();
                    String[] arrOfStr = formapago.split("-");
                    for (int i = 0; i < arrOfStr.length; i++) {
                        String string = arrOfStr[i].trim();

                        if (string.length() > 4) {
                            sriformapago = sriformpagoController.findSriFormaPagoBynombre(string);
                        }
                    }
//                ////////////
                    fpc.setDescripcion(jTextArea1.getText());
                    fpc.setFormaPago(txt_cuentaContable.getText());
                    if (_afectaaCaja) {
                        fpc.setAfectaACaja(1);
                    } else {
                        fpc.setAfectaACaja(0);
                    }
                    fpc.setNumeroCuotas(Integer.parseInt(txt_cuotas.getText()));
                    fpc.setPorcentajeEntrada(Double.parseDouble(txt_entrada.getText()));
                    fpc.setEsCxcCxp(jcb_cxc_cxP.getSelectedItem().toString());
                    fpc.setPlanCodigo(1);
                    fpc.setSriFormaPagoCodigo(sriformapago);
                    fpc.setTipoPago(jcb_formaPago.getSelectedItem().toString());
                    if (jcb_cobranza.getSelectedItem().equals("SELECIONE")) {

                    } else {
                        fpc.setPeridoCobranza(jcb_cobranza.getSelectedItem().toString());
                    }

                    FormaspagocJpaController fpcompracontroller = new FormaspagocJpaController(__factory);
                    if (fpcompracontroller.create(fpc) != null)
                    {
                        try {
                            jProgressBar2.setMaximum(100);
                            jProgressBar2.setStringPainted(true);
                            jProgressBar2.setValue(0);
                            jProgressBar2.setString("EXITO...");                                                                                
                            Thread.sleep(1000);
                            jProgressBar2.setValue(100);                            
                            jProgressBar2.setString("");  
                        } catch (InterruptedException ex) {
                            Logger.getLogger(alerta.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }else{
                    try {
                            jProgressBar2.setMaximum(100);
                            jProgressBar2.setStringPainted(true);
                            jProgressBar2.setString("ERROR");
                            jProgressBar2.repaint();
                            Thread.sleep(3000);
                            jProgressBar2.setMaximum(0);
                            jProgressBar2.setString("");
                            jProgressBar2.repaint();
                        } catch (InterruptedException ex) {
                            Logger.getLogger(alerta.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    
                    }
                    

//            }
//
//        } else {
//            JOptionPane.showMessageDialog(null, "Error Informacion incompleta");
                } else {
                    alerta.progressbar(jProgressBar2, "Error Selecione Tipo Movimiento y Forma de Pago");

                }

    }//GEN-LAST:event_jButton3ActionPerformed
        else {
                alerta.progressbar(jProgressBar2, "Error Selecione Tipo Movimiento y Forma de Pago");

            }
        } catch (Exception e) {

            alerta.progressbar(jProgressBar2, "Error Selecione Tipo Movimiento y Forma de Pago");

        }
    }

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked


    }//GEN-LAST:event_jButton1MouseClicked

    private void txt_cuentaContableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cuentaContableKeyReleased
        // TODO add your handling code here:
        KeysEnventos.uperCaseJTextField(txt_cuentaContable, evt);


    }//GEN-LAST:event_txt_cuentaContableKeyReleased

    private void jrb_afectaCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_afectaCajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_afectaCajaActionPerformed

    private void txt_cuotasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cuotasKeyReleased
        // TODO add your handling code here:
        if (!ValidaNUmeros.isOnlyDouble(txt_cuotas.getText())) {
            evt.consume();
        } else {
            txt_cuotas.setText("1");
        }
    }//GEN-LAST:event_txt_cuotasKeyReleased

    private void txt_cuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cuotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cuotasActionPerformed

    private void jTextArea1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextArea1KeyPressed

    private void jTextArea1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyReleased
        // TODO add your handling code here:
        KeysEnventos.uperCaseJTextaArea(jTextArea1, evt);
    }//GEN-LAST:event_jTextArea1KeyReleased

    private void jcb_cxc_cxPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcb_cxc_cxPItemStateChanged
        // TODO add your handling code here:
        if (jcb_cxc_cxP.getSelectedItem().toString().equalsIgnoreCase("SELECCIONE")) {
            _tipoMovimiento_CXC_CXP_selected = false;
        } else {
            _tipoMovimiento_CXC_CXP_selected = true;

        }
    }//GEN-LAST:event_jcb_cxc_cxPItemStateChanged

    private void jcb_formaPagoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcb_formaPagoItemStateChanged
        // TODO add your handling code here:

        if (!jcb_formaPago.getSelectedItem().toString().equals("SELECIONE")) {
            _FormaPagoSelected = true;
            if (jcb_formaPago.getSelectedItem().toString().equals("EFECTIVO")) {
                jrb_afectaCaja.setSelected(true);
                _afectaaCaja = true;
            } else {
                jrb_afectaCaja.setSelected(false);
                _afectaaCaja = false;
            }

            if (jcb_formaPago.getSelectedItem().toString().equals("CREDITO")) {
                this.setSize(846, 448);

            } else {
                this.setSize(585, 448);
                txt_cuotas.setText("1");
                txt_diasCredito.setText("30");
                txt_entrada.setText("0.0");
                jcb_cobranza.setSelectedItem("SELECCIONE");
            }
            _tipo_forma_pago = jcb_cxc_cxP.getSelectedItem().toString();

        } else {
            _FormaPagoSelected = false;
        }
    }//GEN-LAST:event_jcb_formaPagoItemStateChanged

    private void jrb_afectaCajaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jrb_afectaCajaItemStateChanged
        // TODO add your handling code here:

        if (jcb_formaPago.getSelectedItem().toString().equals("EFECTIVO")) {
            jrb_afectaCaja.setSelected(true);
        } else {
            jrb_afectaCaja.setSelected(false);
        }
    }//GEN-LAST:event_jrb_afectaCajaItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //PlanJpaController planControlller = new PlanJpaController(__factory);
        //Plan cuenta = planControlller.findCuentaByDescripcion("EFECTIVO Y EQUIVALENTES DE EFECTIVO");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_entradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_entradaKeyReleased
        // TODO add your handling code here:

        if (!ValidaNUmeros.isOnlyDouble(txt_entrada.getText())) {
            evt.consume();
        } else {
            txt_entrada.setText("0.0");
        }
    }//GEN-LAST:event_txt_entradaKeyReleased

    private void jcb_cobranzaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcb_cobranzaItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_jcb_cobranzaItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cuentaContable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    public static javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> jcb_cobranza;
    private javax.swing.JComboBox<String> jcb_cxc_cxP;
    private javax.swing.JComboBox<String> jcb_formaPago;
    private javax.swing.JComboBox<String> jcb_sustentoTributario;
    private javax.swing.JRadioButton jrb_afectaCaja;
    private javax.swing.JTextField txt_cuentaContable;
    private javax.swing.JTextField txt_cuotas;
    private javax.swing.JTextField txt_diasCredito;
    private javax.swing.JTextField txt_entrada;
    // End of variables declaration//GEN-END:variables
}
