/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Usuarios;

import Controlador.Usuarios.CajasDetalleDao;
import ClasesAuxiliares.debug.Deb;
import Controlador.Usuarios.FacturasDao;
import Controlador.Usuarios.HoraFecha;
import Controlador.Usuarios.cxcDao;
import Controlador.Usuarios.TicketsDao;
import Modelo.Facturas;
import Modelo.Cxc;
import Modelo.Tickets;
import static Vista.Usuarios.Modal_CrearFacturas.RegistrodeEfectivoyCambioExitoso;
import Vlidaciones.ValidaNUmeros;
import java.awt.event.WindowAdapter;
import login.login;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import org.codehaus.groovy.ast.stmt.DoWhileStatement;

/**
 *
 * @author USUARIO
 */
public class PagoEfectivo extends javax.swing.JDialog {

    double total;
    double abono;
    double saldo;
    public static Facturas fac = new Facturas();
    public static Tickets t = new Tickets();
    Integer codigoFactura;

    boolean isclicked = false;
    Date fecha = new Date();

    /**
     * Creates new form PagoCredito1
     */
    public PagoEfectivo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //bnt_siguente.setEnabled(false);
        HoraFecha ob2 = new HoraFecha();
        fecha = ob2.obtenerFecha();
        
        /// HoraFecha.fecha(fecha)
        rootPane.setDefaultButton(this.bnt_siguente);
        //txt_entrada.transferFocus();
        txt_entrada.grabFocus();
        txt_entrada.selectAll();

    }
    // in = new JTextField(40);

//
//    public Date sumarRestarDiasFecha(Date fecha, int dias) {
//
//        Calendar calendar = Calendar.getInstance();
//        calendar.setTime(fecha); // Configuramos la fecha que se recibe
//        calendar.add(Calendar.DAY_OF_YEAR, dias);  // numero de días a añadir, o restar en caso de días<0
//        return calendar.getTime(); // Devuelve el objeto Date con los nuevos días añadidos
//
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        bnt_siguente2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txt_total = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_cambio = new javax.swing.JTextField();
        txt_entrada = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bnt_siguente = new javax.swing.JButton();
        bnt_siguente1 = new javax.swing.JButton();

        bnt_siguente2.setBackground(new java.awt.Color(255, 0, 51));
        bnt_siguente2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bnt_siguente2.setText("CANCELAR");
        bnt_siguente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_siguente2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("true"), this, org.jdesktop.beansbinding.BeanProperty.create("undecorated"));
        bindingGroup.addBinding(binding);

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("REGISTRAR EFECTIVO"));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txt_total.setEditable(false);

        jLabel1.setText("TOTAL VENTA");

        txt_cambio.setEditable(false);

        txt_entrada.setText("0.00");
        txt_entrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_entradaKeyReleased(evt);
            }
        });

        jLabel2.setText("ENTRADA EN EFECTIVO");

        jLabel3.setText("CAMBIO");

        bnt_siguente.setBackground(new java.awt.Color(255, 204, 0));
        bnt_siguente.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bnt_siguente.setText("ACEPTAR");
        bnt_siguente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_siguenteActionPerformed(evt);
            }
        });

        bnt_siguente1.setBackground(new java.awt.Color(255, 0, 51));
        bnt_siguente1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bnt_siguente1.setText("CANCELAR");
        bnt_siguente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_siguente1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cambio, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bnt_siguente1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(bnt_siguente, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(241, 241, 241))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_total)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_entrada)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_cambio)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bnt_siguente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bnt_siguente1, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("REGISTRO DE EFECTIVO Y CAMBIO", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_entradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_entradaKeyReleased
        // TODO add your handling code here:
        if (ValidaNUmeros.isOnlyDouble(txt_entrada.getText())) {

            if (Double.valueOf(txt_total.getText()) <= Double.valueOf(txt_entrada.getText())) {
                bnt_siguente.setEnabled(true);
                total = Double.valueOf(txt_total.getText().replace(",", "."));
                if (txt_entrada.getText().contains(",")) {
                    abono = Double.valueOf(txt_entrada.getText().replace(",", "."));
                } else {
                    abono = Double.valueOf(txt_entrada.getText());
                }

                saldo = abono - total;

                txt_cambio.setText(String.valueOf(String.format("%.4f", saldo)).replace(",", "."));
            } else {
                txt_cambio.setText("0.00");
            }
        } else {
            txt_entrada.setText("0.0");
            txt_entrada.selectAll();
        }
    }//GEN-LAST:event_txt_entradaKeyReleased

    private void bnt_siguenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_siguenteActionPerformed
        // TODO add your handling code here:

        if (Double.parseDouble(txt_total.getText()) > Double.parseDouble(txt_entrada.getText())) {
            JOptionPane.showMessageDialog(null, "EL EFECTIVO NO CUBRE EL TOTAL DE LA FACTIRA");
            txt_entrada.requestFocus();
           txt_entrada.setText("0.0");
            txt_entrada.selectAll();

        } else {
            Modal_CrearFacturas.efectivo = Double.parseDouble(txt_entrada.getText());
            Modal_CrearFacturas.cambio = Double.parseDouble(txt_cambio.getText());
           
            Modal_CrearFacturas.procedeVentaExitosa=true;
            this.dispose();
        }


    }//GEN-LAST:event_bnt_siguenteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //jDateChooser1.setDate(sumarRestarDiasFecha(fecha,Integer.valueOf(spinerDiasCredito.getValue().toString())));
        isclicked = true;
        Deb.consola("Vista.Usuarios.PagoCredito.jPanel2FocusGained() is clikeddd al opneform");
    }//GEN-LAST:event_formWindowOpened

    private void bnt_siguente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_siguente1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bnt_siguente1ActionPerformed

    private void bnt_siguente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_siguente2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnt_siguente2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagoEfectivo.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagoEfectivo.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagoEfectivo.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagoEfectivo.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PagoEfectivo dialog = new PagoEfectivo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
        public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_siguente;
    private javax.swing.JButton bnt_siguente1;
    private javax.swing.JButton bnt_siguente2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JTextField txt_cambio;
    public static javax.swing.JTextField txt_entrada;
    public static javax.swing.JTextField txt_total;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
