/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Usuarios;

import Controlador.Usuarios.CajasDetalleDao;
import Controlador.Usuarios.FacturasDao;
import Controlador.Usuarios.HoraFecha;
import Controlador.Usuarios.cxcDao;
import Controlador.Usuarios.TicketsDao;
import Modelo.Facturas;
import Modelo.Cxc;
import Modelo.Tickets;
import Vlidaciones.ValidaNUmeros;
import login.login;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import org.codehaus.groovy.ast.stmt.DoWhileStatement;

/**
 *
 * @author USUARIO
 */
public class PagoCredito extends javax.swing.JDialog {
    
    double total;
    double abono;
    double saldo;
    public static Facturas fac = new Facturas();
    public static Tickets t = new Tickets();
    Integer codigoFactura;
    
    boolean isclicked = false;
    Date fecha = new Date();

    /**
     * Creates new form PagoCredito1
     */
    public PagoCredito(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        spinerDiasCredito.setValue(30);
        HoraFecha ob2 = new HoraFecha();
        fecha = ob2.obtenerFecha();
        jDateChooser1.setDate(fecha);
        
        jDateChooser1.setDate(sumarRestarDiasFecha(fecha, Integer.valueOf(spinerDiasCredito.getValue().toString())));
        txt_entrada.grabFocus();        
        txt_entrada.selectAll();
        /// HoraFecha.fecha(fecha)
        rootPane.setDefaultButton(this.bnt_siguente);
        
    }
    
    public Date sumarRestarDiasFecha(Date fecha, int dias) {
        
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(fecha); // Configuramos la fecha que se recibe
        calendar.add(Calendar.DAY_OF_YEAR, dias);  // numero de días a añadir, o restar en caso de días<0
        return calendar.getTime(); // Devuelve el objeto Date con los nuevos días añadidos

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bnt_siguente2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txt_total = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_saldo = new javax.swing.JTextField();
        txt_entrada = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bnt_siguente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        spinerDiasCredito = new javax.swing.JSpinner();
        bnt_siguente3 = new javax.swing.JButton();
        bnt_siguente1 = new javax.swing.JButton();

        bnt_siguente2.setBackground(new java.awt.Color(255, 0, 51));
        bnt_siguente2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bnt_siguente2.setText("CANCELAR");
        bnt_siguente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_siguente2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("VENTA A CREDITO"));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txt_total.setEditable(false);

        jLabel1.setText("VALOR CREDITO");

        txt_saldo.setEditable(false);

        txt_entrada.setText("0.00");
        txt_entrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_entradaKeyReleased(evt);
            }
        });

        jLabel2.setText("ENTRADA EN EFECTIVO");

        jLabel3.setText("SALDO ");

        bnt_siguente.setBackground(new java.awt.Color(255, 204, 0));
        bnt_siguente.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bnt_siguente.setText("SIGUIENTE");
        bnt_siguente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_siguenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(287, 287, 287))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bnt_siguente, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_total)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_entrada)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_saldo)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(bnt_siguente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("VALORES DEL CREDITO", jPanel1);

        jPanel2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel2FocusGained(evt);
            }
        });

        jDateChooser1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jDateChooser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateChooser1MouseClicked(evt);
            }
        });
        jDateChooser1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jDateChooser1KeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("DIAS DE CREDITO");

        jButton2.setBackground(new java.awt.Color(0, 204, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setText("FINALIZAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("FECHA DE VENCIMIENTO");

        spinerDiasCredito.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        spinerDiasCredito.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinerDiasCreditoStateChanged(evt);
            }
        });
        spinerDiasCredito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spinerDiasCreditoMouseClicked(evt);
            }
        });
        spinerDiasCredito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                spinerDiasCreditoKeyReleased(evt);
            }
        });

        bnt_siguente3.setBackground(new java.awt.Color(255, 153, 153));
        bnt_siguente3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bnt_siguente3.setText("ATRAS");
        bnt_siguente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_siguente3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinerDiasCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(bnt_siguente3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bnt_siguente3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinerDiasCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CALENDARIO DEL CREDITO", jPanel2);

        bnt_siguente1.setBackground(new java.awt.Color(255, 0, 51));
        bnt_siguente1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bnt_siguente1.setText("CANCELAR");
        bnt_siguente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_siguente1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bnt_siguente1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bnt_siguente1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_entradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_entradaKeyReleased
        // TODO add your handling code here:
        if (ValidaNUmeros.isOnlyDouble(txt_entrada.getText())) {
            
            if (Double.valueOf(txt_total.getText()) > Double.valueOf(txt_entrada.getText())) {
                
                total = Double.valueOf(txt_total.getText().replace(",", "."));
                if (txt_entrada.getText().contains(",")) {
                    abono = Double.valueOf(txt_entrada.getText().replace(",", "."));
                } else {
                    abono = Double.valueOf(txt_entrada.getText());
                }
                
                saldo = total - abono;
                
                String sald = String.valueOf(String.format("%.4f", saldo));
                saldo = Double.valueOf(sald.replace(",", "."));
                
                txt_saldo.setText(String.valueOf(saldo));
            } else {
                //  System.out.println("Vista.Usuarios.PagoCredito.txt_entradaKeyReleased()auuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu");
                JOptionPane.showMessageDialog(null, "El valor de Entrada del Credito no puede ser Mayor al Total de la Venta");
                txt_entrada.requestFocus();
                txt_entrada.setText("0.0");
                txt_entrada.selectAll();
                
            }
        } else {
            txt_entrada.setText("0.0");
            txt_entrada.selectAll();
        }
    }//GEN-LAST:event_txt_entradaKeyReleased

    private void bnt_siguenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_siguenteActionPerformed
        // TODO add your handling code here:
        // System.out.println("Vista.Usuarios.PagoCredito.jPanel2FocusGained() is clikeddd");
        isclicked = true;
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_bnt_siguenteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        Cxc cxc = new Cxc();
        cxcDao cxcDao = new cxcDao();
        cxc.setDescripcion(Crear_Facturas.tipoDocumento + " -- FORMA DE PAGO : " + Crear_Facturas.formaPagoSeelccionada + " DESDE : " + login.nombreDelEquipo);
        cxc.setTotal(txt_total.getText());
        cxc.setTipo(Crear_Facturas.tipoDocumento);
        cxc.setAbono(txt_entrada.getText());
        
        total = Double.valueOf(txt_total.getText().replace(",", "."));
        if (txt_entrada.getText().contains(",")) {
            abono = Double.valueOf(txt_entrada.getText().replace(",", "."));
        } else {
            abono = Double.valueOf(txt_entrada.getText());
        }
        saldo = total - abono;        
        cxc.setSaldo(String.valueOf(String.format("%.4f", total)));        
        cxc.setFormasPagoV_codigo(Crear_Facturas.codigFormaPagoSeleccionada);
        cxc.setSaldo(String.valueOf(this.saldo));
        
        if (Crear_Facturas.tipoDocumento.equals("FACTURA")) {
            FacturasDao fDao = new FacturasDao();
            codigoFactura = fDao.guardar(fac);
        }
        if (Crear_Facturas.tipoDocumento.equals("TICKET")) {
            TicketsDao tDao = new TicketsDao();
            codigoFactura = tDao.guardar(t);
        }
        
        Crear_Facturas.codigoFactura = codigoFactura;
        cxc.setFacturas_codigo(codigoFactura);
        cxc.setDiasCredito(spinerDiasCredito.getValue().toString());
        // System.out.println("Vista.Usuarios.PagoCredito.jButton2ActionPerformed() dias credito :" + spinerDiasCredito.getValue().toString());
        cxc.setFechaVencimiento(jDateChooser1.getDate());
        cxc.setClientes_Codigo(Crear_Facturas.codigoClienteFactura);        
        cxcDao.guardar(cxc);
        CajasDetalleDao cdDao = new CajasDetalleDao();
        Crear_Facturas.cd.setCodigoDocuemnto(codigoFactura);        
        
        if (txt_entrada.getText().equals("0.0")) {
            // System.out.println("Vista.Usuarios.PagoCredito.jButton2ActionPerformed(): "+);    
            cdDao.guardar(Crear_Facturas.cd);
        } else {
            //Crear_Facturas.cd.setDetalle(" - ABONO: "+Crear_Facturas.cd.getDetalle()+" - TOTAL VENTA: "+total+" - TOTAL ABONO: "+abono+" - SALDO: "+saldo);
            Crear_Facturas.cd.setDetalle("ABONO - VENTA  " + Crear_Facturas.tipoDocumento + " - " + Crear_Facturas.jcbFormasPago.getSelectedItem().toString() + " # " + Crear_Facturas.secuenciaFac + " EN EQUIPO: " + login.nombreDelEquipo + " USUARIO: " + login.nombresUsuario + " - SALDO: " + saldo);
            Crear_Facturas.cd.setValor(abono);            
            cdDao.guardar(Crear_Facturas.cd);
            CajasDetalleDao cdDao1 = new CajasDetalleDao();
            Crear_Facturas.cd.setDetalle("SALDO - VENTA  " + Crear_Facturas.tipoDocumento + " - " + Crear_Facturas.jcbFormasPago.getSelectedItem().toString() + " # " + Crear_Facturas.secuenciaFac + " EN EQUIPO: " + login.nombreDelEquipo + " USUARIO: " + login.nombresUsuario + " - SALDO: " + saldo);
            Crear_Facturas.cd.setValor(saldo);            
            cdDao1.guardar(Crear_Facturas.cd);
        }

        //   System.out.println("Vista.Usuarios.PagoCredito.jButton2ActionPerformed()se registro el ");
        Crear_Facturas.procedeVentaExitosa = true;
        this.dispose();
        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jDateChooser1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooser1KeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jDateChooser1KeyReleased

    private void jDateChooser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jDateChooser1MouseClicked

    private void spinerDiasCreditoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spinerDiasCreditoKeyReleased
        // TODO add your handling code here:
        if(spinerDiasCredito.getValue().toString().contains("-")){
        spinerDiasCredito.setValue(0);
        }

    }//GEN-LAST:event_spinerDiasCreditoKeyReleased

    private void spinerDiasCreditoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spinerDiasCreditoMouseClicked
        // TODO add your handling code here:
if(spinerDiasCredito.getValue().toString().contains("-")){
        spinerDiasCredito.setValue(0);
        }

    }//GEN-LAST:event_spinerDiasCreditoMouseClicked

    private void spinerDiasCreditoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinerDiasCreditoStateChanged
        // TODO add your handling code here:
        if (isclicked) {
            jDateChooser1.setDate(sumarRestarDiasFecha(fecha, Integer.valueOf(spinerDiasCredito.getValue().toString())));
            System.out.println("Vista.Usuarios.PagoCredito.spinerDiasCreditoKeyReleased() estaechange");
        }
    }//GEN-LAST:event_spinerDiasCreditoStateChanged

    private void jPanel2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel2FocusGained
        // TODO add your handling code here:
        isclicked = true;
        System.out.println("Vista.Usuarios.PagoCredito.jPanel2FocusGained() is clikeddd");
    }//GEN-LAST:event_jPanel2FocusGained

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //jDateChooser1.setDate(sumarRestarDiasFecha(fecha,Integer.valueOf(spinerDiasCredito.getValue().toString())));
        isclicked = true;
        System.out.println("Vista.Usuarios.PagoCredito.jPanel2FocusGained() is clikeddd al opneform");
    }//GEN-LAST:event_formWindowOpened

    private void bnt_siguente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_siguente1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bnt_siguente1ActionPerformed

    private void bnt_siguente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_siguente2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnt_siguente2ActionPerformed

    private void bnt_siguente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_siguente3ActionPerformed
        // TODO add your handling code here:
        isclicked = true;
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_bnt_siguente3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagoCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagoCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagoCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagoCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PagoCredito dialog = new PagoCredito(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_siguente;
    private javax.swing.JButton bnt_siguente1;
    private javax.swing.JButton bnt_siguente2;
    private javax.swing.JButton bnt_siguente3;
    private javax.swing.JButton jButton2;
    public static com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JSpinner spinerDiasCredito;
    public static javax.swing.JTextField txt_entrada;
    public static javax.swing.JTextField txt_saldo;
    public static javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
