/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Usuarios;

import Controlador.Usuarios.CajasDao;
import Modelo.Cajas;
import static Vista.Usuarios.NuevoEquipo.cajaNombre;
import java.awt.Component;
import static java.awt.font.GlyphMetrics.COMPONENT;
import java.util.ArrayList;
import javax.swing.SwingUtilities;

/**
 *
 * @author USUARIO
 */
public class SelectCaja extends javax.swing.JDialog {

    /**
     * Creates new form SelectCaja
     */
    ArrayList<Cajas> lista = new ArrayList<Cajas>();
    public static boolean esllamadodesdeNuevoEquipo = false;

    public SelectCaja(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Cajas caja = new Cajas();
        CajasDao cajaDao = new CajasDao();
        lista = cajaDao.listar();
        for (Cajas cajas : lista) {
            jComboBox1.addItem(cajas.getCaja());
            System.out.println("Cajassss: " + cajas.getCaja());
        }
//        if (!esllamadodesdeNuevoEquipo) {
//            System.out.println("Caja Cliked" + Configuracion.cajaClicked);
//            jComboBox1.setSelectedItem(Configuracion.cajaClicked);
//        } else {
//            jComboBox1.setSelectedItem("seleccione");
//        }
//setLocationRelativeTo(Congifuracion.BOTTOM_ALIGNMENT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        txt_codigo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Seleccione Caja");
        setModal(true);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        jComboBox1.setName(""); // NOI18N
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        System.out.println("Vista.Usuarios.SelectCaja.jComboBox1ItemStateChanged()se ha seleccinadosss");
        if (jComboBox1.getSelectedItem() != null) {
            for (Cajas cajas : lista) {
                if (jComboBox1.getSelectedItem().toString().equals(cajas.getCaja())) {
                    txt_codigo.setText(cajas.getCodigo().toString());
                    Configuracion.codigoCaja = cajas.getCodigo();
                    Configuracion.cajaClicked = cajas.getCaja();
//                    if (esllamadodesdeNuevoEquipo) {
//                        NuevoEquipo.cajaCodigo = cajas.getCodigo();
//                        NuevoEquipo.cajaNombre = cajas.getCaja();
//                      //  NuevoEquipo.txtCaja.setText(cajas.getCaja());
//                    }
                    dispose();
                }
                if (jComboBox1.getSelectedItem().toString().equals("Seleccione")) {
                    Configuracion.codigoCaja = cajas.getCodigo();
                    txt_codigo.setText("...");
                    Configuracion.codigoCaja = 0;
                    NuevoEquipo.cajaCodigo = 0;
                    NuevoEquipo.cajaNombre = "N/A";
                }

            }
        }

    }//GEN-LAST:event_jComboBox1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SelectCaja dialog = new SelectCaja(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel txt_codigo;
    // End of variables declaration//GEN-END:variables
}
