/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Sat;

import ClasesAuxiliares.debug.Deb;
import Controlador.Ejemplo;
import Controlador.Sat.SatAparatoDao;
import Controlador.Sat.SatOrdenDao;
import Controlador.Sat.SatOrdenDetalleDao;
import Controlador.Sat.SatSerieDao;
import Modelo.Clientes;
import Modelo.SatAparato;
import Modelo.SatOrden;
import Modelo.SatOrdenDetalle;
import Modelo.SatSeries;
import Vista.Principal;
import Vista.Usuarios.Crear_Clientes;
import Vista.Usuarios.PagoEfectivo;
import Vlidaciones.ValidaNUmeros;
import com.mxrck.autocompleter.AutoCompleterCallback;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class Crear_Orden extends javax.swing.JInternalFrame {

    /**
     * Creates new form crearEquipo
     */
    private List<SatAparato> listaAparatos = new ArrayList<SatAparato>();
    public static Clientes newCliente = new Clientes();
    Integer clienteCodigo = null;
    public static Integer aparatoCodigo = null;
    Integer OrdenCodigo = null;
    TextAutoCompleter autocompleteSeries = null;
    ArrayList<SatSeries> lista_Series = new ArrayList<SatSeries>();
    Integer codigoSerie = -1;
    String serieSeleccionada = "";

    public Crear_Orden() {
        initComponents();
        txtAccesorios.setLineWrap(true);
        txtAccesorios.setWrapStyleWord(true);
        txtObservaciones.setLineWrap(true);
        txtObservaciones.setWrapStyleWord(true);
        txt_danoreportado.setLineWrap(true);
        txt_danoreportado.setWrapStyleWord(true);

        txtDiagnostico.setLineWrap(true);
        txtDiagnostico.setWrapStyleWord(true);
        txtHistorial.setLineWrap(true);
        txtHistorial.setWrapStyleWord(true);
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setWrapStyleWord(true);
        newCliente = null;
//this.setSize(719, 619);
        llenarNextNumeroOrdenLBL();
        //SatOrden satOrden1 = new SatOrden();
        SatSerieDao objSeriesDao = new SatSerieDao();
        lista_Series = objSeriesDao.listar();
////autocomplete

        autocompleteSeries = new TextAutoCompleter(txtSerie, new AutoCompleterCallback() {

            @Override
            public void callback(Object selectedItem) {

                if (selectedItem instanceof SatSeries) {
                    SatSeries c = new SatSeries();
                    c = ((SatSeries) selectedItem);
                    txtSerie.setText(c.getSerie());
                    codigoSerie = c.getCodigo();
                    serieSeleccionada = c.getSerie();
                    txtMarca.transferFocus();

                } else {
                    Deb.consola("El item es de un tipo desconocido");
                }

            }
        });
        autocompleteSeries.setCaseSensitive(false);
        autocompleteSeries.setMode(0);
        for (SatSeries p : lista_Series) {
            autocompleteSeries.addItem(p);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtRUC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtMarca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtParte = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jcbAparatos = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        txtSerie = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_danoreportado = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAccesorios = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txt_numeroOrden = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        txtPresupuesto = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtHistorial = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtDiagnostico = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Crear Orden de Ingreso ");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Aparato"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Cliente"));

        txtRUC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRUCActionPerformed(evt);
            }
        });
        txtRUC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRUCKeyPressed(evt);
            }
        });

        jLabel1.setText("RUC/CI: ");

        jLabel2.setText("Nombres");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtRUC, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtNombres))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRUC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 18, 352, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Aparatos Registrados"));

        txtMarca.setEditable(false);

        jLabel4.setText("Marca");

        jLabel5.setText("Modelo: ");

        txtModelo.setEditable(false);
        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });

        jLabel6.setText("Numero de Pate");

        txtParte.setEditable(false);

        jLabel7.setText("Color");

        txtColor.setEditable(false);

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane3.setViewportView(txtObservaciones);

        jLabel9.setText("Observaciones");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane6.setViewportView(txtDescripcion);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtParte, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane6))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtParte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 195, -1, 300));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Aparatos"));

        jcbAparatos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbAparatosItemStateChanged(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 204, 102));
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtSerie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSerieKeyPressed(evt);
            }
        });

        jLabel8.setText("Serie: ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbAparatos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSerie, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jcbAparatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 104, 352, 80));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Daño Reportado"));

        txt_danoreportado.setColumns(20);
        txt_danoreportado.setRows(5);
        jScrollPane2.setViewportView(txt_danoreportado);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 206, -1, 289));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Accesorios"));

        txtAccesorios.setColumns(20);
        txtAccesorios.setRows(5);
        jScrollPane1.setViewportView(txtAccesorios);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 18, 333, -1));

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton3.setBackground(new java.awt.Color(255, 102, 51));
        jButton3.setText("CANCELAR");

        jButton4.setBackground(new java.awt.Color(0, 204, 102));
        jButton4.setText("GUARDAR ORDEN");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txt_numeroOrden.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_numeroOrden.setForeground(new java.awt.Color(255, 0, 0));

        jLabel10.setText("Orden N.- ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_numeroOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_numeroOrden, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 513, 692, -1));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Presupuesto"));

        txtPresupuesto.setText("0.0");
        txtPresupuesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPresupuestoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(txtPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(txtPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 160, 60));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Historial"));

        txtHistorial.setColumns(20);
        txtHistorial.setRows(5);
        jScrollPane4.setViewportView(txtHistorial);

        jLabel11.setText("Problemas Reportadors");

        txtDiagnostico.setColumns(20);
        txtDiagnostico.setRows(5);
        jScrollPane5.setViewportView(txtDiagnostico);

        jLabel12.setText("Diagnostico y Recomendaciones");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
            .addComponent(jScrollPane5)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, 420, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRUCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRUCKeyPressed
        // TODO add your handling code here:
        if ((evt.getKeyCode() == KeyEvent.VK_ENTER && txtRUC.getText().length() == 10) || (evt.getKeyCode() == KeyEvent.VK_ENTER && txtRUC.getText().length() == 13)) {
            Crear_Clientes.isLlamadoDesdeNuevoAparato = true;
            if (Crear_Clientes.buscarOCrearNuevoCLientevERIFICA(txtRUC.getText())) {
                txtNombres.setText(newCliente.getNombre());

                SatAparato aparato = new SatAparato();
                SatAparatoDao aparatoDao = new SatAparatoDao();
                Deb.consola("Vista.Sat.Crear_Orden.txtRUCKeyPressed() : " + jcbAparatos.getItemCount());
                //if(jcbAparatos.getItemCount()>0){
                jcbAparatos.removeAllItems();
                // }                
                listaAparatos = aparatoDao.buscarAparatoPorIDCliente(newCliente.getCodigo().toString());
                for (SatAparato a : listaAparatos) {
                    jcbAparatos.addItem(a.getDescripcion() + " Serie: " + a.getSerie());
                }
            } else {
                Crear_Clientes c = new Crear_Clientes();
                c.buscarOCrearNuevoCLiente(txtRUC.getText());
                Principal.desktopPane.add(c);
                c.setVisible(true);
//                Deb.consola("LLL: " + newCliente.getNombre());
                if (newCliente != null) {
                    txtNombres.setText(newCliente.getNombre());

                    SatAparato aparato = new SatAparato();
                    SatAparatoDao aparatoDao = new SatAparatoDao();
                    Deb.consola("Vista.Sat.Crear_Orden.txtRUCKeyPreHHHHHHHHHssed() : " + jcbAparatos.getItemCount());
                    //if(jcbAparatos.getItemCount()>0){
                    jcbAparatos.removeAllItems();
                    // }                
                    listaAparatos = aparatoDao.buscarAparatoPorIDCliente(newCliente.getCodigo().toString());
                    for (SatAparato a : listaAparatos) {
                        jcbAparatos.addItem(a.getDescripcion() + " Serie: " + a.getSerie());
                    }
                }
            }

        }//else{
        //    JOptionPane.showMessageDialog(null, "Numero de Identificacion invaclido ","ERROR", JOptionPane.ERROR_MESSAGE, frameIcon);
        // }
    }//GEN-LAST:event_txtRUCKeyPressed

    private void llenarNextNumeroOrdenLBL() {
        SatOrdenDao satOrdenDao1 = new SatOrdenDao();
        String n = satOrdenDao1.getNextNueroDeOrden();
        Integer num = Integer.valueOf(n);
        // txt_numeroOrden.setText();
        DecimalFormat formateador = new DecimalFormat("000000000");
        String format = formateador.format(num);
        txt_numeroOrden.setText(String.valueOf(format));
    }


    private void txtRUCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRUCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRUCActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (newCliente != null && !txtNombres.getText().equals("") && !txtRUC.getText().equals("")) {
            SatAparatoDao aparatoDao = new SatAparatoDao();
            Frame ff = JOptionPane.getFrameForComponent(this);
            New_Aparato dialog = new New_Aparato(ff, true);
            dialog.cliente = this.newCliente;
            dialog.setVisible(true);
            listaAparatos = aparatoDao.buscarAparatoPorIDCliente(newCliente.getCodigo().toString());
            jcbAparatos.removeAllItems();
            for (SatAparato a : listaAparatos) {
                jcbAparatos.addItem(a.getDescripcion());
            }

//            Crear_Aparato ca = new Crear_Aparato();
//            ca.cliente = newCliente;
//            Principal.desktopPane.add(ca);
//            ca.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Selccione un cliente Valido ", "ERROR", JOptionPane.ERROR_MESSAGE, frameIcon);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jcbAparatosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbAparatosItemStateChanged
        // TODO add your handling code here:
        if (jcbAparatos.getItemCount() > 0) {
            for (SatAparato l : listaAparatos) {
                if ((jcbAparatos.getSelectedItem().toString()).contains(l.getSerie())) {
//            txtColor.setText(l.getColor());
                    aparatoCodigo = l.getCodigo();
                    txtDescripcion.setText(l.getDescripcion());
                    txtMarca.setText(l.getMarca());
                    txtModelo.setText(l.getModelo());
                    txtObservaciones.setText(l.getObservaciones());
                    txtParte.setText(l.getParte());
                    txtSerie.setText(l.getSerie());

                }

            }
        } else {
            vaciartxt();
        }

    }//GEN-LAST:event_jcbAparatosItemStateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:        
        if (!txtSerie.getText().equals("") || jcbAparatos.getItemCount() > 0) {
            SatOrdenDetalle satOrdenDetalle = new SatOrdenDetalle();
            SatOrdenDetalleDao satOrdenDetalleDao = new SatOrdenDetalleDao();
            SatOrden satOrden = new SatOrden();
            SatOrdenDao satOrdenDao = new SatOrdenDao();
            satOrden.setClientes_codigo(newCliente.getCodigo());
            satOrden.setDescripcion(txtObservaciones.getText());
            satOrden.setNumero(txt_numeroOrden.getText());
            satOrden.setUsuarios_codigo(login.login.CodigoUsuario);
            //OrdenDetalle
            satOrdenDetalle.setCerrado(0);
            satOrdenDetalle.setAccesorios(txtAccesorios.getText());
            satOrdenDetalle.setPresupuesto(Double.parseDouble(txtPresupuesto.getText().replace(",", ".")));
            satOrdenDetalle.setEstado("1");
            OrdenCodigo = satOrdenDao.guardar(satOrden);
            satOrdenDetalle.setSatorden_codigo(OrdenCodigo);
            satOrdenDetalle.setSatAparato_codigo(aparatoCodigo);
            satOrdenDetalleDao.guardar(satOrdenDetalle);
            llenarNextNumeroOrdenLBL();
            vaciartxt();

        } else {
            JOptionPane.showMessageDialog(null, "SELECCIONA UN APARATO REGISTRADO ", "ERROR", JOptionPane.ERROR_MESSAGE, frameIcon);
        }

        ////guardar

    }//GEN-LAST:event_jButton4ActionPerformed
    private void vaciartxt() {
        txtAccesorios.setText("");
        txtColor.setText("");
        txtDescripcion.setText("");
        txtHistorial.setText("");
        txtMarca.setText("");
        txtModelo.setText("");
        txtObservaciones.setText("");
        txtParte.setText("");
        txtPresupuesto.setText("0.0");
        txtSerie.setText("");
        txt_danoreportado.setText("");
    }
    private void txtPresupuestoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPresupuestoKeyReleased
        // TODO add your handling code here:
        ValidaNUmeros.isOnlyDouble(txtPresupuesto.getText());
    }//GEN-LAST:event_txtPresupuestoKeyReleased

    private void txtSerieKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSerieKeyPressed
        // TODO add your handling code here:
        SatSeries satSeries = new SatSeries();
        SatSerieDao satSeriesDao = new SatSerieDao();
        SatAparato satAparato = new SatAparato();
        SatAparatoDao satAparatoDao = new SatAparatoDao();
        //satSeries=   satSeriesDao.buscarSerieAparato(txtSerie.getText());
        //if(satSeries.getSerie()!=null){
        if (evt.getKeyCode() == com.sun.glass.events.KeyEvent.VK_ENTER) {
            satAparato = satAparatoDao.buscarAparatoSerie(txtSerie.getText());
            if (satAparato.getSerie() != null) {
                txtMarca.setText(satAparato.getMarca());
                aparatoCodigo = satAparato.getCodigo();
                txtDescripcion.setText(satAparato.getDescripcion());
                txtMarca.setText(satAparato.getMarca());
                txtModelo.setText(satAparato.getModelo());
                txtObservaciones.setText(satAparato.getObservaciones());
                txtParte.setText(satAparato.getParte());
                txtSerie.setText(satAparato.getSerie());
            } else {
                if (newCliente != null && !txtNombres.getText().equals("") && !txtRUC.getText().equals("")) {
                    SatAparatoDao aparatoDao = new SatAparatoDao();
                    Frame ff = JOptionPane.getFrameForComponent(this);
                    New_Aparato dialog = new New_Aparato(ff, true);
                    dialog.cliente = this.newCliente;
                    dialog.txtseries.setText(txtSerie.getText());
                    dialog.setVisible(true);
                    listaAparatos = aparatoDao.buscarAparatoPorIDCliente(newCliente.getCodigo().toString());
                    jcbAparatos.removeAllItems();
                    for (SatAparato a : listaAparatos) {
                        jcbAparatos.addItem(a.getDescripcion());
                    }

//            Crear_Aparato ca = new Crear_Aparato();
//            ca.cliente = newCliente;
//            Principal.desktopPane.add(ca);
//            ca.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Selccione un cliente Valido ", "ERROR", JOptionPane.ERROR_MESSAGE, frameIcon);
                }

            }

        }

        //}

    }//GEN-LAST:event_txtSerieKeyPressed

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JComboBox<String> jcbAparatos;
    private javax.swing.JTextArea txtAccesorios;
    public static javax.swing.JTextField txtColor;
    public static javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextArea txtDiagnostico;
    private javax.swing.JTextArea txtHistorial;
    public static javax.swing.JTextField txtMarca;
    public static javax.swing.JTextField txtModelo;
    public static javax.swing.JTextField txtNombres;
    public static javax.swing.JTextArea txtObservaciones;
    public static javax.swing.JTextField txtParte;
    private javax.swing.JTextField txtPresupuesto;
    public static javax.swing.JTextField txtRUC;
    public static javax.swing.JTextField txtSerie;
    private javax.swing.JTextArea txt_danoreportado;
    private javax.swing.JLabel txt_numeroOrden;
    // End of variables declaration//GEN-END:variables
}
